/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * List user actions and configuration changes within this organization.
 * @summary List audit logs
 */
export const listAuditLogsQueryLimitDefault = 20;

export const listAuditLogsQueryParams = zod.object({
  "effective_at": zod.object({
  "gt": zod.number().optional().describe('Return only events whose `effective_at` (Unix seconds) is greater than this value.'),
  "gte": zod.number().optional().describe('Return only events whose `effective_at` (Unix seconds) is greater than or equal to this value.'),
  "lt": zod.number().optional().describe('Return only events whose `effective_at` (Unix seconds) is less than this value.'),
  "lte": zod.number().optional().describe('Return only events whose `effective_at` (Unix seconds) is less than or equal to this value.')
}).optional().describe('Return only events whose `effective_at` (Unix seconds) is in this range.'),
  "project_ids[]": zod.array(zod.string()).optional().describe('Return only events for these projects.'),
  "event_types[]": zod.array(zod.enum(['api_key.created', 'api_key.updated', 'api_key.deleted', 'certificate.created', 'certificate.updated', 'certificate.deleted', 'certificates.activated', 'certificates.deactivated', 'checkpoint.permission.created', 'checkpoint.permission.deleted', 'external_key.registered', 'external_key.removed', 'group.created', 'group.updated', 'group.deleted', 'invite.sent', 'invite.accepted', 'invite.deleted', 'ip_allowlist.created', 'ip_allowlist.updated', 'ip_allowlist.deleted', 'ip_allowlist.config.activated', 'ip_allowlist.config.deactivated', 'login.succeeded', 'login.failed', 'logout.succeeded', 'logout.failed', 'organization.updated', 'project.created', 'project.updated', 'project.archived', 'project.deleted', 'rate_limit.updated', 'rate_limit.deleted', 'resource.deleted', 'role.created', 'role.updated', 'role.deleted', 'role.assignment.created', 'role.assignment.deleted', 'scim.enabled', 'scim.disabled', 'service_account.created', 'service_account.updated', 'service_account.deleted', 'user.added', 'user.updated', 'user.deleted']).describe('The event type.')).optional().describe('Return only events with a `type` in one of these values. For example, `project.created`. For all options, see the documentation for the [audit log object](https://platform.openai.com/docs/api-reference/audit-logs/object).'),
  "actor_ids[]": zod.array(zod.string()).optional().describe('Return only events performed by these actors. Can be a user ID, a service account ID, or an api key tracking ID.'),
  "actor_emails[]": zod.array(zod.string()).optional().describe('Return only events performed by users with these emails.'),
  "resource_ids[]": zod.array(zod.string()).optional().describe('Return only events performed on these targets. For example, a project ID updated.'),
  "limit": zod.number().optional().describe('A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.\n'),
  "after": zod.string().optional().describe('A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.\n'),
  "before": zod.string().optional().describe('A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with obj_foo, your subsequent call can include before=obj_foo in order to fetch the previous page of the list.\n')
})

export const listAuditLogsResponse = zod.object({
  "object": zod.enum(['list']),
  "data": zod.array(zod.object({
  "id": zod.string().describe('The ID of this log.'),
  "type": zod.enum(['api_key.created', 'api_key.updated', 'api_key.deleted', 'certificate.created', 'certificate.updated', 'certificate.deleted', 'certificates.activated', 'certificates.deactivated', 'checkpoint.permission.created', 'checkpoint.permission.deleted', 'external_key.registered', 'external_key.removed', 'group.created', 'group.updated', 'group.deleted', 'invite.sent', 'invite.accepted', 'invite.deleted', 'ip_allowlist.created', 'ip_allowlist.updated', 'ip_allowlist.deleted', 'ip_allowlist.config.activated', 'ip_allowlist.config.deactivated', 'login.succeeded', 'login.failed', 'logout.succeeded', 'logout.failed', 'organization.updated', 'project.created', 'project.updated', 'project.archived', 'project.deleted', 'rate_limit.updated', 'rate_limit.deleted', 'resource.deleted', 'role.created', 'role.updated', 'role.deleted', 'role.assignment.created', 'role.assignment.deleted', 'scim.enabled', 'scim.disabled', 'service_account.created', 'service_account.updated', 'service_account.deleted', 'user.added', 'user.updated', 'user.deleted']).describe('The event type.'),
  "effective_at": zod.number().describe('The Unix timestamp (in seconds) of the event.'),
  "project": zod.object({
  "id": zod.string().optional().describe('The project ID.'),
  "name": zod.string().optional().describe('The project title.')
}).optional().describe('The project that the action was scoped to. Absent for actions not scoped to projects. Note that any admin actions taken via Admin API keys are associated with the default project.'),
  "actor": zod.object({
  "type": zod.enum(['session', 'api_key']).optional().describe('The type of actor. Is either `session` or `api_key`.'),
  "session": zod.object({
  "user": zod.object({
  "id": zod.string().optional().describe('The user id.'),
  "email": zod.string().optional().describe('The user email.')
}).optional().describe('The user who performed the audit logged action.'),
  "ip_address": zod.string().optional().describe('The IP address from which the action was performed.')
}).optional().describe('The session in which the audit logged action was performed.'),
  "api_key": zod.object({
  "id": zod.string().optional().describe('The tracking id of the API key.'),
  "type": zod.enum(['user', 'service_account']).optional().describe('The type of API key. Can be either `user` or `service_account`.'),
  "user": zod.object({
  "id": zod.string().optional().describe('The user id.'),
  "email": zod.string().optional().describe('The user email.')
}).optional().describe('The user who performed the audit logged action.'),
  "service_account": zod.object({
  "id": zod.string().optional().describe('The service account id.')
}).optional().describe('The service account that performed the audit logged action.')
}).optional().describe('The API Key used to perform the audit logged action.')
}).describe('The actor who performed the audit logged action.'),
  "api_key.created": zod.object({
  "id": zod.string().optional().describe('The tracking ID of the API key.'),
  "data": zod.object({
  "scopes": zod.array(zod.string()).optional().describe('A list of scopes allowed for the API key, e.g. `[\"api.model.request\"]`')
}).optional().describe('The payload used to create the API key.')
}).optional().describe('The details for events with this `type`.'),
  "api_key.updated": zod.object({
  "id": zod.string().optional().describe('The tracking ID of the API key.'),
  "changes_requested": zod.object({
  "scopes": zod.array(zod.string()).optional().describe('A list of scopes allowed for the API key, e.g. `[\"api.model.request\"]`')
}).optional().describe('The payload used to update the API key.')
}).optional().describe('The details for events with this `type`.'),
  "api_key.deleted": zod.object({
  "id": zod.string().optional().describe('The tracking ID of the API key.')
}).optional().describe('The details for events with this `type`.'),
  "checkpoint.permission.created": zod.object({
  "id": zod.string().optional().describe('The ID of the checkpoint permission.'),
  "data": zod.object({
  "project_id": zod.string().optional().describe('The ID of the project that the checkpoint permission was created for.'),
  "fine_tuned_model_checkpoint": zod.string().optional().describe('The ID of the fine-tuned model checkpoint.')
}).optional().describe('The payload used to create the checkpoint permission.')
}).optional().describe('The project and fine-tuned model checkpoint that the checkpoint permission was created for.'),
  "checkpoint.permission.deleted": zod.object({
  "id": zod.string().optional().describe('The ID of the checkpoint permission.')
}).optional().describe('The details for events with this `type`.'),
  "external_key.registered": zod.object({
  "id": zod.string().optional().describe('The ID of the external key configuration.'),
  "data": zod.object({

}).optional().describe('The configuration for the external key.')
}).optional().describe('The details for events with this `type`.'),
  "external_key.removed": zod.object({
  "id": zod.string().optional().describe('The ID of the external key configuration.')
}).optional().describe('The details for events with this `type`.'),
  "group.created": zod.object({
  "id": zod.string().optional().describe('The ID of the group.'),
  "data": zod.object({
  "group_name": zod.string().optional().describe('The group name.')
}).optional().describe('Information about the created group.')
}).optional().describe('The details for events with this `type`.'),
  "group.updated": zod.object({
  "id": zod.string().optional().describe('The ID of the group.'),
  "changes_requested": zod.object({
  "group_name": zod.string().optional().describe('The updated group name.')
}).optional().describe('The payload used to update the group.')
}).optional().describe('The details for events with this `type`.'),
  "group.deleted": zod.object({
  "id": zod.string().optional().describe('The ID of the group.')
}).optional().describe('The details for events with this `type`.'),
  "scim.enabled": zod.object({
  "id": zod.string().optional().describe('The ID of the SCIM was enabled for.')
}).optional().describe('The details for events with this `type`.'),
  "scim.disabled": zod.object({
  "id": zod.string().optional().describe('The ID of the SCIM was disabled for.')
}).optional().describe('The details for events with this `type`.'),
  "invite.sent": zod.object({
  "id": zod.string().optional().describe('The ID of the invite.'),
  "data": zod.object({
  "email": zod.string().optional().describe('The email invited to the organization.'),
  "role": zod.string().optional().describe('The role the email was invited to be. Is either `owner` or `member`.')
}).optional().describe('The payload used to create the invite.')
}).optional().describe('The details for events with this `type`.'),
  "invite.accepted": zod.object({
  "id": zod.string().optional().describe('The ID of the invite.')
}).optional().describe('The details for events with this `type`.'),
  "invite.deleted": zod.object({
  "id": zod.string().optional().describe('The ID of the invite.')
}).optional().describe('The details for events with this `type`.'),
  "ip_allowlist.created": zod.object({
  "id": zod.string().optional().describe('The ID of the IP allowlist configuration.'),
  "name": zod.string().optional().describe('The name of the IP allowlist configuration.'),
  "allowed_ips": zod.array(zod.string()).optional().describe('The IP addresses or CIDR ranges included in the configuration.')
}).optional().describe('The details for events with this `type`.'),
  "ip_allowlist.updated": zod.object({
  "id": zod.string().optional().describe('The ID of the IP allowlist configuration.'),
  "allowed_ips": zod.array(zod.string()).optional().describe('The updated set of IP addresses or CIDR ranges in the configuration.')
}).optional().describe('The details for events with this `type`.'),
  "ip_allowlist.deleted": zod.object({
  "id": zod.string().optional().describe('The ID of the IP allowlist configuration.'),
  "name": zod.string().optional().describe('The name of the IP allowlist configuration.'),
  "allowed_ips": zod.array(zod.string()).optional().describe('The IP addresses or CIDR ranges that were in the configuration.')
}).optional().describe('The details for events with this `type`.'),
  "ip_allowlist.config.activated": zod.object({
  "configs": zod.array(zod.object({
  "id": zod.string().optional().describe('The ID of the IP allowlist configuration.'),
  "name": zod.string().optional().describe('The name of the IP allowlist configuration.')
})).optional().describe('The configurations that were activated.')
}).optional().describe('The details for events with this `type`.'),
  "ip_allowlist.config.deactivated": zod.object({
  "configs": zod.array(zod.object({
  "id": zod.string().optional().describe('The ID of the IP allowlist configuration.'),
  "name": zod.string().optional().describe('The name of the IP allowlist configuration.')
})).optional().describe('The configurations that were deactivated.')
}).optional().describe('The details for events with this `type`.'),
  "login.succeeded": zod.object({

}).optional().describe('This event has no additional fields beyond the standard audit log attributes.'),
  "login.failed": zod.object({
  "error_code": zod.string().optional().describe('The error code of the failure.'),
  "error_message": zod.string().optional().describe('The error message of the failure.')
}).optional().describe('The details for events with this `type`.'),
  "logout.succeeded": zod.object({

}).optional().describe('This event has no additional fields beyond the standard audit log attributes.'),
  "logout.failed": zod.object({
  "error_code": zod.string().optional().describe('The error code of the failure.'),
  "error_message": zod.string().optional().describe('The error message of the failure.')
}).optional().describe('The details for events with this `type`.'),
  "organization.updated": zod.object({
  "id": zod.string().optional().describe('The organization ID.'),
  "changes_requested": zod.object({
  "title": zod.string().optional().describe('The organization title.'),
  "description": zod.string().optional().describe('The organization description.'),
  "name": zod.string().optional().describe('The organization name.'),
  "threads_ui_visibility": zod.string().optional().describe('Visibility of the threads page which shows messages created with the Assistants API and Playground. One of `ANY_ROLE`, `OWNERS`, or `NONE`.'),
  "usage_dashboard_visibility": zod.string().optional().describe('Visibility of the usage dashboard which shows activity and costs for your organization. One of `ANY_ROLE` or `OWNERS`.'),
  "api_call_logging": zod.string().optional().describe('How your organization logs data from supported API calls. One of `disabled`, `enabled_per_call`, `enabled_for_all_projects`, or `enabled_for_selected_projects`'),
  "api_call_logging_project_ids": zod.string().optional().describe('The list of project ids if api_call_logging is set to `enabled_for_selected_projects`')
}).optional().describe('The payload used to update the organization settings.')
}).optional().describe('The details for events with this `type`.'),
  "project.created": zod.object({
  "id": zod.string().optional().describe('The project ID.'),
  "data": zod.object({
  "name": zod.string().optional().describe('The project name.'),
  "title": zod.string().optional().describe('The title of the project as seen on the dashboard.')
}).optional().describe('The payload used to create the project.')
}).optional().describe('The details for events with this `type`.'),
  "project.updated": zod.object({
  "id": zod.string().optional().describe('The project ID.'),
  "changes_requested": zod.object({
  "title": zod.string().optional().describe('The title of the project as seen on the dashboard.')
}).optional().describe('The payload used to update the project.')
}).optional().describe('The details for events with this `type`.'),
  "project.archived": zod.object({
  "id": zod.string().optional().describe('The project ID.')
}).optional().describe('The details for events with this `type`.'),
  "project.deleted": zod.object({
  "id": zod.string().optional().describe('The project ID.')
}).optional().describe('The details for events with this `type`.'),
  "rate_limit.updated": zod.object({
  "id": zod.string().optional().describe('The rate limit ID'),
  "changes_requested": zod.object({
  "max_requests_per_1_minute": zod.number().optional().describe('The maximum requests per minute.'),
  "max_tokens_per_1_minute": zod.number().optional().describe('The maximum tokens per minute.'),
  "max_images_per_1_minute": zod.number().optional().describe('The maximum images per minute. Only relevant for certain models.'),
  "max_audio_megabytes_per_1_minute": zod.number().optional().describe('The maximum audio megabytes per minute. Only relevant for certain models.'),
  "max_requests_per_1_day": zod.number().optional().describe('The maximum requests per day. Only relevant for certain models.'),
  "batch_1_day_max_input_tokens": zod.number().optional().describe('The maximum batch input tokens per day. Only relevant for certain models.')
}).optional().describe('The payload used to update the rate limits.')
}).optional().describe('The details for events with this `type`.'),
  "rate_limit.deleted": zod.object({
  "id": zod.string().optional().describe('The rate limit ID')
}).optional().describe('The details for events with this `type`.'),
  "role.created": zod.object({
  "id": zod.string().optional().describe('The role ID.'),
  "role_name": zod.string().optional().describe('The name of the role.'),
  "permissions": zod.array(zod.string()).optional().describe('The permissions granted by the role.'),
  "resource_type": zod.string().optional().describe('The type of resource the role belongs to.'),
  "resource_id": zod.string().optional().describe('The resource the role is scoped to.')
}).optional().describe('The details for events with this `type`.'),
  "role.updated": zod.object({
  "id": zod.string().optional().describe('The role ID.'),
  "changes_requested": zod.object({
  "role_name": zod.string().optional().describe('The updated role name, when provided.'),
  "resource_id": zod.string().optional().describe('The resource the role is scoped to.'),
  "resource_type": zod.string().optional().describe('The type of resource the role belongs to.'),
  "permissions_added": zod.array(zod.string()).optional().describe('The permissions added to the role.'),
  "permissions_removed": zod.array(zod.string()).optional().describe('The permissions removed from the role.'),
  "description": zod.string().optional().describe('The updated role description, when provided.'),
  "metadata": zod.object({

}).optional().describe('Additional metadata stored on the role.')
}).optional().describe('The payload used to update the role.')
}).optional().describe('The details for events with this `type`.'),
  "role.deleted": zod.object({
  "id": zod.string().optional().describe('The role ID.')
}).optional().describe('The details for events with this `type`.'),
  "role.assignment.created": zod.object({
  "id": zod.string().optional().describe('The identifier of the role assignment.'),
  "principal_id": zod.string().optional().describe('The principal (user or group) that received the role.'),
  "principal_type": zod.string().optional().describe('The type of principal (user or group) that received the role.'),
  "resource_id": zod.string().optional().describe('The resource the role assignment is scoped to.'),
  "resource_type": zod.string().optional().describe('The type of resource the role assignment is scoped to.')
}).optional().describe('The details for events with this `type`.'),
  "role.assignment.deleted": zod.object({
  "id": zod.string().optional().describe('The identifier of the role assignment.'),
  "principal_id": zod.string().optional().describe('The principal (user or group) that had the role removed.'),
  "principal_type": zod.string().optional().describe('The type of principal (user or group) that had the role removed.'),
  "resource_id": zod.string().optional().describe('The resource the role assignment was scoped to.'),
  "resource_type": zod.string().optional().describe('The type of resource the role assignment was scoped to.')
}).optional().describe('The details for events with this `type`.'),
  "service_account.created": zod.object({
  "id": zod.string().optional().describe('The service account ID.'),
  "data": zod.object({
  "role": zod.string().optional().describe('The role of the service account. Is either `owner` or `member`.')
}).optional().describe('The payload used to create the service account.')
}).optional().describe('The details for events with this `type`.'),
  "service_account.updated": zod.object({
  "id": zod.string().optional().describe('The service account ID.'),
  "changes_requested": zod.object({
  "role": zod.string().optional().describe('The role of the service account. Is either `owner` or `member`.')
}).optional().describe('The payload used to updated the service account.')
}).optional().describe('The details for events with this `type`.'),
  "service_account.deleted": zod.object({
  "id": zod.string().optional().describe('The service account ID.')
}).optional().describe('The details for events with this `type`.'),
  "user.added": zod.object({
  "id": zod.string().optional().describe('The user ID.'),
  "data": zod.object({
  "role": zod.string().optional().describe('The role of the user. Is either `owner` or `member`.')
}).optional().describe('The payload used to add the user to the project.')
}).optional().describe('The details for events with this `type`.'),
  "user.updated": zod.object({
  "id": zod.string().optional().describe('The project ID.'),
  "changes_requested": zod.object({
  "role": zod.string().optional().describe('The role of the user. Is either `owner` or `member`.')
}).optional().describe('The payload used to update the user.')
}).optional().describe('The details for events with this `type`.'),
  "user.deleted": zod.object({
  "id": zod.string().optional().describe('The user ID.')
}).optional().describe('The details for events with this `type`.'),
  "certificate.created": zod.object({
  "id": zod.string().optional().describe('The certificate ID.'),
  "name": zod.string().optional().describe('The name of the certificate.')
}).optional().describe('The details for events with this `type`.'),
  "certificate.updated": zod.object({
  "id": zod.string().optional().describe('The certificate ID.'),
  "name": zod.string().optional().describe('The name of the certificate.')
}).optional().describe('The details for events with this `type`.'),
  "certificate.deleted": zod.object({
  "id": zod.string().optional().describe('The certificate ID.'),
  "name": zod.string().optional().describe('The name of the certificate.'),
  "certificate": zod.string().optional().describe('The certificate content in PEM format.')
}).optional().describe('The details for events with this `type`.'),
  "certificates.activated": zod.object({
  "certificates": zod.array(zod.object({
  "id": zod.string().optional().describe('The certificate ID.'),
  "name": zod.string().optional().describe('The name of the certificate.')
})).optional()
}).optional().describe('The details for events with this `type`.'),
  "certificates.deactivated": zod.object({
  "certificates": zod.array(zod.object({
  "id": zod.string().optional().describe('The certificate ID.'),
  "name": zod.string().optional().describe('The name of the certificate.')
})).optional()
}).optional().describe('The details for events with this `type`.')
}).describe('A log of a user action or configuration change within this organization.')),
  "first_id": zod.string(),
  "last_id": zod.string(),
  "has_more": zod.boolean()
})

