/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * List stored Chat Completions. Only Chat Completions that have been stored
with the `store` parameter set to `true` will be returned.

 * @summary List Chat Completions
 */
export const listChatCompletionsQueryLimitDefault = 20;export const listChatCompletionsQueryOrderDefault = "asc";

export const listChatCompletionsQueryParams = zod.object({
  "model": zod.string().optional().describe('The model used to generate the Chat Completions.'),
  "metadata": zod.record(zod.string(), zod.string()).describe('Set of 16 key-value pairs that can be attached to an object. This can be\nuseful for storing additional information about the object in a structured\nformat, and querying for objects via API or the dashboard.\n\nKeys are strings with a maximum length of 64 characters. Values are strings\nwith a maximum length of 512 characters.\n').or(zod.null()).optional().describe('A list of metadata keys to filter the Chat Completions by. Example:\n\n`metadata[key1]=value1&metadata[key2]=value2`\n'),
  "after": zod.string().optional().describe('Identifier for the last chat completion from the previous pagination request.'),
  "limit": zod.number().optional().describe('Number of Chat Completions to retrieve.'),
  "order": zod.enum(['asc', 'desc']).optional().describe('Sort order for Chat Completions by timestamp. Use `asc` for ascending order or `desc` for descending order. Defaults to `asc`.')
})

export const listChatCompletionsResponseObjectDefault = "list";export const listChatCompletionsResponseDataItemServiceTierDefaultOne = "auto";export const listChatCompletionsResponseDataItemUsageCompletionTokensDefault = 0;export const listChatCompletionsResponseDataItemUsagePromptTokensDefault = 0;export const listChatCompletionsResponseDataItemUsageTotalTokensDefault = 0;export const listChatCompletionsResponseDataItemUsageCompletionTokensDetailsAcceptedPredictionTokensDefault = 0;export const listChatCompletionsResponseDataItemUsageCompletionTokensDetailsAudioTokensDefault = 0;export const listChatCompletionsResponseDataItemUsageCompletionTokensDetailsReasoningTokensDefault = 0;export const listChatCompletionsResponseDataItemUsageCompletionTokensDetailsRejectedPredictionTokensDefault = 0;export const listChatCompletionsResponseDataItemUsagePromptTokensDetailsAudioTokensDefault = 0;export const listChatCompletionsResponseDataItemUsagePromptTokensDetailsCachedTokensDefault = 0;

export const listChatCompletionsResponse = zod.object({
  "object": zod.enum(['list']).optional().describe('The type of this object. It is always set to \"list\".\n'),
  "data": zod.array(zod.object({
  "id": zod.string().describe('A unique identifier for the chat completion.'),
  "choices": zod.array(zod.object({
  "finish_reason": zod.enum(['stop', 'length', 'tool_calls', 'content_filter', 'function_call']).describe('The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,\n`length` if the maximum number of tokens specified in the request was reached,\n`content_filter` if content was omitted due to a flag from our content filters,\n`tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.\n'),
  "index": zod.number().describe('The index of the choice in the list of choices.'),
  "message": zod.object({
  "content": zod.string().describe('The contents of the message.').or(zod.null()),
  "refusal": zod.string().describe('The refusal message generated by the model.').or(zod.null()),
  "tool_calls": zod.array(zod.discriminatedUnion('type', [zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "name": zod.string().describe('The name of the function to call.'),
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.')
}).describe('The function that the model called.')
}).describe('A call to a function tool created by the model.\n'),zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['custom']).describe('The type of the tool. Always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool to call.'),
  "input": zod.string().describe('The input for the custom tool call generated by the model.')
}).describe('The custom tool that the model called.')
}).describe('A call to a custom tool created by the model.\n')])).optional().describe('The tool calls generated by the model, such as function calls.'),
  "annotations": zod.array(zod.object({
  "type": zod.enum(['url_citation']).describe('The type of the URL citation. Always `url_citation`.'),
  "url_citation": zod.object({
  "end_index": zod.number().describe('The index of the last character of the URL citation in the message.'),
  "start_index": zod.number().describe('The index of the first character of the URL citation in the message.'),
  "url": zod.string().describe('The URL of the web resource.'),
  "title": zod.string().describe('The title of the web resource.')
}).describe('A URL citation when using web search.')
}).describe('A URL citation when using web search.\n')).optional().describe('Annotations for the message, when applicable, as when using the\n[web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).\n'),
  "role": zod.enum(['assistant']).describe('The role of the author of this message.'),
  "function_call": zod.object({
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.'),
  "name": zod.string().describe('The name of the function to call.')
}).optional().describe('Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.'),
  "audio": zod.object({
  "id": zod.string().describe('Unique identifier for this audio response.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when this audio response will\nno longer be accessible on the server for use in multi-turn\nconversations.\n'),
  "data": zod.string().describe('Base64 encoded audio bytes generated by the model, in the format\nspecified in the request.\n'),
  "transcript": zod.string().describe('Transcript of the audio generated by the model.')
}).describe('If the audio output modality is requested, this object contains data\nabout the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).\n').or(zod.null()).optional()
}).describe('A chat completion message generated by the model.'),
  "logprobs": zod.object({
  "content": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message content tokens with log probability information.').or(zod.null()),
  "refusal": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message refusal tokens with log probability information.').or(zod.null())
}).describe('Log probability information for the choice.').or(zod.null())
})).describe('A list of chat completion choices. Can be more than one if `n` is greater than 1.'),
  "created": zod.number().describe('The Unix timestamp (in seconds) of when the chat completion was created.'),
  "model": zod.string().describe('The model used for the chat completion.'),
  "service_tier": zod.enum(['auto', 'default', 'flex', 'scale', 'priority']).optional().describe('Specifies the processing type used for serving the request.\n  - If set to \'auto\', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use \'default\'.\n  - If set to \'default\', then the request will be processed with the standard pricing and performance for the selected model.\n  - If set to \'[flex](https://platform.openai.com/docs/guides/flex-processing)\' or \'[priority](https://openai.com/api-priority-processing/)\', then the request will be processed with the corresponding service tier.\n  - When not set, the default behavior is \'auto\'.\n\n  When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter.\n').or(zod.null()).optional(),
  "system_fingerprint": zod.string().optional().describe('This fingerprint represents the backend configuration that the model runs with.\n\nCan be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.\n'),
  "object": zod.enum(['chat.completion']).describe('The object type, which is always `chat.completion`.'),
  "usage": zod.object({
  "completion_tokens": zod.number().optional().describe('Number of tokens in the generated completion.'),
  "prompt_tokens": zod.number().optional().describe('Number of tokens in the prompt.'),
  "total_tokens": zod.number().optional().describe('Total number of tokens used in the request (prompt + completion).'),
  "completion_tokens_details": zod.object({
  "accepted_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that appeared in the completion.\n'),
  "audio_tokens": zod.number().optional().describe('Audio input tokens generated by the model.'),
  "reasoning_tokens": zod.number().optional().describe('Tokens generated by the model for reasoning.'),
  "rejected_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that did not appear in the completion. However, like\nreasoning tokens, these tokens are still counted in the total\ncompletion tokens for purposes of billing, output, and context window\nlimits.\n')
}).optional().describe('Breakdown of tokens used in a completion.'),
  "prompt_tokens_details": zod.object({
  "audio_tokens": zod.number().optional().describe('Audio input tokens present in the prompt.'),
  "cached_tokens": zod.number().optional().describe('Cached tokens present in the prompt.')
}).optional().describe('Breakdown of tokens used in the prompt.')
}).optional().describe('Usage statistics for the completion request.')
}).describe('Represents a chat completion response returned by model, based on the provided input.')).describe('An array of chat completion objects.\n'),
  "first_id": zod.string().describe('The identifier of the first chat completion in the data array.'),
  "last_id": zod.string().describe('The identifier of the last chat completion in the data array.'),
  "has_more": zod.boolean().describe('Indicates whether there are more Chat Completions available.')
}).describe('An object representing a list of Chat Completions.\n')

/**
 * **Starting a new project?** We recommend trying [Responses](https://platform.openai.com/docs/api-reference/responses)
to take advantage of the latest OpenAI platform features. Compare
[Chat Completions with Responses](https://platform.openai.com/docs/guides/responses-vs-chat-completions?api-mode=responses).

---

Creates a model response for the given chat conversation. Learn more in the
[text generation](https://platform.openai.com/docs/guides/text-generation), [vision](https://platform.openai.com/docs/guides/vision),
and [audio](https://platform.openai.com/docs/guides/audio) guides.

Parameter support can differ depending on the model used to generate the
response, particularly for newer reasoning models. Parameters that are only
supported for reasoning models are noted below. For the current state of
unsupported parameters in reasoning models,
[refer to the reasoning guide](https://platform.openai.com/docs/guides/reasoning).

 * @summary Create chat completion
 */
export const createChatCompletionBodyTopLogprobsMinOne = 0;
export const createChatCompletionBodyTopLogprobsMaxOne = 20;
export const createChatCompletionBodyTemperatureDefaultOne = 1;export const createChatCompletionBodyTemperatureMinOne = 0;
export const createChatCompletionBodyTemperatureMaxOne = 2;
export const createChatCompletionBodyTopPDefaultOne = 1;export const createChatCompletionBodyTopPMinOne = 0;
export const createChatCompletionBodyTopPMaxOne = 1;
export const createChatCompletionBodyServiceTierDefaultOne = "auto";export const createChatCompletionBodyTopLogprobsMinThree = 0;

export const createChatCompletionBodyTopLogprobsMaxThree = 20;
export const createChatCompletionBodyMessagesItemContentItemImageUrlDetailDefault = "auto";export const createChatCompletionBodyVerbosityDefaultOne = "medium";export const createChatCompletionBodyReasoningEffortDefaultOne = "medium";export const createChatCompletionBodyFrequencyPenaltyDefault = 0;
export const createChatCompletionBodyFrequencyPenaltyMin = -2;

export const createChatCompletionBodyFrequencyPenaltyMax = 2;
export const createChatCompletionBodyPresencePenaltyDefault = 0;
export const createChatCompletionBodyPresencePenaltyMin = -2;

export const createChatCompletionBodyPresencePenaltyMax = 2;
export const createChatCompletionBodyWebSearchOptionsSearchContextSizeDefault = "medium";export const createChatCompletionBodyTopLogprobsMinFour = 0;

export const createChatCompletionBodyTopLogprobsMaxFour = 20;
export const createChatCompletionBodyResponseFormatJsonSchemaStrictDefaultOne = false;export const createChatCompletionBodyStoreDefault = false;export const createChatCompletionBodyStreamDefault = false;export const createChatCompletionBodyStopDefaultOne = "<|endoftext|>";export const createChatCompletionBodyStopMaxTwo = 4;
export const createChatCompletionBodyLogitBiasDefault = null;export const createChatCompletionBodyLogprobsDefault = false;export const createChatCompletionBodyNDefault = 1;
export const createChatCompletionBodyNMax = 128;
export const createChatCompletionBodySeedMin = -9223372036854776000;

export const createChatCompletionBodySeedMax = 9223372036854776000;
export const createChatCompletionBodyToolsItemFunctionStrictDefaultOne = false;export const createChatCompletionBodyParallelToolCallsDefault = true;export const createChatCompletionBodyFunctionsMax = 128;


export const createChatCompletionBody = zod.object({
  "metadata": zod.record(zod.string(), zod.string()).describe('Set of 16 key-value pairs that can be attached to an object. This can be\nuseful for storing additional information about the object in a structured\nformat, and querying for objects via API or the dashboard.\n\nKeys are strings with a maximum length of 64 characters. Values are strings\nwith a maximum length of 512 characters.\n').or(zod.null()).optional(),
  "top_logprobs": zod.number().min(createChatCompletionBodyTopLogprobsMinOne).max(createChatCompletionBodyTopLogprobsMaxOne).describe('An integer between 0 and 20 specifying the number of most likely tokens to\nreturn at each token position, each with an associated log probability.\n').or(zod.null()).optional(),
  "temperature": zod.number().min(createChatCompletionBodyTemperatureMinOne).max(createChatCompletionBodyTemperatureMaxOne).optional().describe('What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.\nWe generally recommend altering this or `top_p` but not both.\n').or(zod.null()).optional(),
  "top_p": zod.number().min(createChatCompletionBodyTopPMinOne).max(createChatCompletionBodyTopPMaxOne).optional().describe('An alternative to sampling with temperature, called nucleus sampling,\nwhere the model considers the results of the tokens with top_p probability\nmass. So 0.1 means only the tokens comprising the top 10% probability mass\nare considered.\n\nWe generally recommend altering this or `temperature` but not both.\n').or(zod.null()).optional(),
  "user": zod.string().optional().describe('This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to maintain caching optimizations.\nA stable identifier for your end-users.\nUsed to boost cache hit rates by better bucketing similar requests and  to help OpenAI detect and prevent abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).\n'),
  "safety_identifier": zod.string().optional().describe('A stable identifier used to help detect users of your application that may be violating OpenAI\'s usage policies.\nThe IDs should be a string that uniquely identifies each user. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).\n'),
  "prompt_cache_key": zod.string().optional().describe('Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](https://platform.openai.com/docs/guides/prompt-caching).\n'),
  "service_tier": zod.enum(['auto', 'default', 'flex', 'scale', 'priority']).optional().describe('Specifies the processing type used for serving the request.\n  - If set to \'auto\', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use \'default\'.\n  - If set to \'default\', then the request will be processed with the standard pricing and performance for the selected model.\n  - If set to \'[flex](https://platform.openai.com/docs/guides/flex-processing)\' or \'[priority](https://openai.com/api-priority-processing/)\', then the request will be processed with the corresponding service tier.\n  - When not set, the default behavior is \'auto\'.\n\n  When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter.\n').or(zod.null()).optional()
}).and(zod.object({
  "top_logprobs": zod.number().min(createChatCompletionBodyTopLogprobsMinThree).max(createChatCompletionBodyTopLogprobsMaxThree).optional().describe('An integer between 0 and 20 specifying the number of most likely tokens to\nreturn at each token position, each with an associated log probability.\n')
})).and(zod.object({
  "messages": zod.array(zod.discriminatedUnion('role', [zod.object({
  "content": zod.string().describe('The contents of the developer message.').or(zod.array(zod.object({
  "type": zod.enum(['text']).describe('The type of the content part.'),
  "text": zod.string().describe('The text content.')
}).describe('Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).\n')).min(1).describe('An array of content parts with a defined type. For developer messages, only type `text` is supported.')).describe('The contents of the developer message.'),
  "role": zod.enum(['developer']).describe('The role of the messages author, in this case `developer`.'),
  "name": zod.string().optional().describe('An optional name for the participant. Provides the model information to differentiate between participants of the same role.')
}).describe('Developer-provided instructions that the model should follow, regardless of\nmessages sent by the user. With o1 models and newer, `developer` messages\nreplace the previous `system` messages.\n'),zod.object({
  "content": zod.string().describe('The contents of the system message.').or(zod.array(zod.object({
  "type": zod.enum(['text']).describe('The type of the content part.'),
  "text": zod.string().describe('The text content.')
}).describe('Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).\n')).min(1).describe('An array of content parts with a defined type. For system messages, only type `text` is supported.')).describe('The contents of the system message.'),
  "role": zod.enum(['system']).describe('The role of the messages author, in this case `system`.'),
  "name": zod.string().optional().describe('An optional name for the participant. Provides the model information to differentiate between participants of the same role.')
}).describe('Developer-provided instructions that the model should follow, regardless of\nmessages sent by the user. With o1 models and newer, use `developer` messages\nfor this purpose instead.\n'),zod.object({
  "content": zod.string().describe('The text contents of the message.').or(zod.array(zod.discriminatedUnion('type', [zod.object({
  "type": zod.enum(['text']).describe('The type of the content part.'),
  "text": zod.string().describe('The text content.')
}).describe('Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).\n'),zod.object({
  "type": zod.enum(['image_url']).describe('The type of the content part.'),
  "image_url": zod.object({
  "url": zod.string().url().describe('Either a URL of the image or the base64 encoded image data.'),
  "detail": zod.enum(['auto', 'low', 'high']).optional().describe('Specifies the detail level of the image. Learn more in the [Vision guide](https://platform.openai.com/docs/guides/vision#low-or-high-fidelity-image-understanding).')
})
}).describe('Learn about [image inputs](https://platform.openai.com/docs/guides/vision).\n'),zod.object({
  "type": zod.enum(['input_audio']).describe('The type of the content part. Always `input_audio`.'),
  "input_audio": zod.object({
  "data": zod.string().describe('Base64 encoded audio data.'),
  "format": zod.enum(['wav', 'mp3']).describe('The format of the encoded audio data. Currently supports \"wav\" and \"mp3\".\n')
})
}).describe('Learn about [audio inputs](https://platform.openai.com/docs/guides/audio).\n'),zod.object({
  "type": zod.enum(['file']).describe('The type of the content part. Always `file`.'),
  "file": zod.object({
  "filename": zod.string().optional().describe('The name of the file, used when passing the file to the model as a\nstring.\n'),
  "file_data": zod.string().optional().describe('The base64 encoded file data, used when passing the file to the model\nas a string.\n'),
  "file_id": zod.string().optional().describe('The ID of an uploaded file to use as input.\n')
})
}).describe('Learn about [file inputs](https://platform.openai.com/docs/guides/text) for text generation.\n')])).min(1).describe('An array of content parts with a defined type. Supported options differ based on the [model](https://platform.openai.com/docs/models) being used to generate the response. Can contain text, image, or audio inputs.')).describe('The contents of the user message.\n'),
  "role": zod.enum(['user']).describe('The role of the messages author, in this case `user`.'),
  "name": zod.string().optional().describe('An optional name for the participant. Provides the model information to differentiate between participants of the same role.')
}).describe('Messages sent by an end user, containing prompts or additional context\ninformation.\n'),zod.object({
  "content": zod.string().describe('The contents of the assistant message.').or(zod.array(zod.discriminatedUnion('type', [zod.object({
  "type": zod.enum(['text']).describe('The type of the content part.'),
  "text": zod.string().describe('The text content.')
}).describe('Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).\n'),zod.object({
  "type": zod.enum(['refusal']).describe('The type of the content part.'),
  "refusal": zod.string().describe('The refusal message generated by the model.')
})])).min(1).describe('An array of content parts with a defined type. Can be one or more of type `text`, or exactly one of type `refusal`.')).describe('The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.\n').or(zod.null()).optional(),
  "refusal": zod.string().describe('The refusal message by the assistant.').or(zod.null()).optional(),
  "role": zod.enum(['assistant']).describe('The role of the messages author, in this case `assistant`.'),
  "name": zod.string().optional().describe('An optional name for the participant. Provides the model information to differentiate between participants of the same role.'),
  "audio": zod.object({
  "id": zod.string().describe('Unique identifier for a previous audio response from the model.\n')
}).describe('Data about a previous audio response from the model.\n[Learn more](https://platform.openai.com/docs/guides/audio).\n').or(zod.null()).optional(),
  "tool_calls": zod.array(zod.discriminatedUnion('type', [zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "name": zod.string().describe('The name of the function to call.'),
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.')
}).describe('The function that the model called.')
}).describe('A call to a function tool created by the model.\n'),zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['custom']).describe('The type of the tool. Always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool to call.'),
  "input": zod.string().describe('The input for the custom tool call generated by the model.')
}).describe('The custom tool that the model called.')
}).describe('A call to a custom tool created by the model.\n')])).optional().describe('The tool calls generated by the model, such as function calls.'),
  "function_call": zod.object({
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.'),
  "name": zod.string().describe('The name of the function to call.')
}).describe('Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.').or(zod.null()).optional()
}).describe('Messages sent by the model in response to user messages.\n'),zod.object({
  "role": zod.enum(['tool']).describe('The role of the messages author, in this case `tool`.'),
  "content": zod.string().describe('The contents of the tool message.').or(zod.array(zod.object({
  "type": zod.enum(['text']).describe('The type of the content part.'),
  "text": zod.string().describe('The text content.')
}).describe('Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).\n')).min(1).describe('An array of content parts with a defined type. For tool messages, only type `text` is supported.')).describe('The contents of the tool message.'),
  "tool_call_id": zod.string().describe('Tool call that this message is responding to.')
}),zod.object({
  "role": zod.enum(['function']).describe('The role of the messages author, in this case `function`.'),
  "content": zod.string().describe('The contents of the function message.').or(zod.null()),
  "name": zod.string().describe('The name of the function to call.')
})])).min(1).describe('A list of messages comprising the conversation so far. Depending on the\n[model](https://platform.openai.com/docs/models) you use, different message types (modalities) are\nsupported, like [text](https://platform.openai.com/docs/guides/text-generation),\n[images](https://platform.openai.com/docs/guides/vision), and [audio](https://platform.openai.com/docs/guides/audio).\n'),
  "model": zod.string().or(zod.enum(['gpt-5', 'gpt-5-mini', 'gpt-5-nano', 'gpt-5-2025-08-07', 'gpt-5-mini-2025-08-07', 'gpt-5-nano-2025-08-07', 'gpt-5-chat-latest', 'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'gpt-4.1-2025-04-14', 'gpt-4.1-mini-2025-04-14', 'gpt-4.1-nano-2025-04-14', 'o4-mini', 'o4-mini-2025-04-16', 'o3', 'o3-2025-04-16', 'o3-mini', 'o3-mini-2025-01-31', 'o1', 'o1-2024-12-17', 'o1-preview', 'o1-preview-2024-09-12', 'o1-mini', 'o1-mini-2024-09-12', 'gpt-4o', 'gpt-4o-2024-11-20', 'gpt-4o-2024-08-06', 'gpt-4o-2024-05-13', 'gpt-4o-audio-preview', 'gpt-4o-audio-preview-2024-10-01', 'gpt-4o-audio-preview-2024-12-17', 'gpt-4o-audio-preview-2025-06-03', 'gpt-4o-mini-audio-preview', 'gpt-4o-mini-audio-preview-2024-12-17', 'gpt-4o-search-preview', 'gpt-4o-mini-search-preview', 'gpt-4o-search-preview-2025-03-11', 'gpt-4o-mini-search-preview-2025-03-11', 'chatgpt-4o-latest', 'codex-mini-latest', 'gpt-4o-mini', 'gpt-4o-mini-2024-07-18', 'gpt-4-turbo', 'gpt-4-turbo-2024-04-09', 'gpt-4-0125-preview', 'gpt-4-turbo-preview', 'gpt-4-1106-preview', 'gpt-4-vision-preview', 'gpt-4', 'gpt-4-0314', 'gpt-4-0613', 'gpt-4-32k', 'gpt-4-32k-0314', 'gpt-4-32k-0613', 'gpt-3.5-turbo', 'gpt-3.5-turbo-16k', 'gpt-3.5-turbo-0301', 'gpt-3.5-turbo-0613', 'gpt-3.5-turbo-1106', 'gpt-3.5-turbo-0125', 'gpt-3.5-turbo-16k-0613'])),
  "modalities": zod.array(zod.enum(['text', 'audio'])).describe('Output types that you would like the model to generate.\nMost models are capable of generating text, which is the default:\n\n`[\"text\"]`\n\nThe `gpt-4o-audio-preview` model can also be used to\n[generate audio](https://platform.openai.com/docs/guides/audio). To request that this model generate\nboth text and audio responses, you can use:\n\n`[\"text\", \"audio\"]`\n').or(zod.null()).optional(),
  "verbosity": zod.enum(['low', 'medium', 'high']).optional().describe('Constrains the verbosity of the model\'s response. Lower values will result in\nmore concise responses, while higher values will result in more verbose responses.\nCurrently supported values are `low`, `medium`, and `high`.\n').or(zod.null()).optional(),
  "reasoning_effort": zod.enum(['minimal', 'low', 'medium', 'high']).optional().describe('Constrains effort on reasoning for\n[reasoning models](https://platform.openai.com/docs/guides/reasoning).\nCurrently supported values are `minimal`, `low`, `medium`, and `high`. Reducing\nreasoning effort can result in faster responses and fewer tokens used\non reasoning in a response.\n\nNote: The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.\n').or(zod.null()).optional(),
  "max_completion_tokens": zod.number().nullish().describe('An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).\n'),
  "frequency_penalty": zod.number().min(createChatCompletionBodyFrequencyPenaltyMin).max(createChatCompletionBodyFrequencyPenaltyMax).nullish().describe('Number between -2.0 and 2.0. Positive values penalize new tokens based on\ntheir existing frequency in the text so far, decreasing the model\'s\nlikelihood to repeat the same line verbatim.\n'),
  "presence_penalty": zod.number().min(createChatCompletionBodyPresencePenaltyMin).max(createChatCompletionBodyPresencePenaltyMax).nullish().describe('Number between -2.0 and 2.0. Positive values penalize new tokens based on\nwhether they appear in the text so far, increasing the model\'s likelihood\nto talk about new topics.\n'),
  "web_search_options": zod.object({
  "user_location": zod.object({
  "type": zod.enum(['approximate']).describe('The type of location approximation. Always `approximate`.\n'),
  "approximate": zod.object({
  "country": zod.string().optional().describe('The two-letter\n[ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user,\ne.g. `US`.\n'),
  "region": zod.string().optional().describe('Free text input for the region of the user, e.g. `California`.\n'),
  "city": zod.string().optional().describe('Free text input for the city of the user, e.g. `San Francisco`.\n'),
  "timezone": zod.string().optional().describe('The [IANA timezone](https://timeapi.io/documentation/iana-timezones)\nof the user, e.g. `America/Los_Angeles`.\n')
}).describe('Approximate location parameters for the search.')
}).nullish().describe('Approximate location parameters for the search.\n'),
  "search_context_size": zod.enum(['low', 'medium', 'high']).optional().describe('High level guidance for the amount of context window space to use for the\nsearch. One of `low`, `medium`, or `high`. `medium` is the default.\n')
}).optional().describe('This tool searches the web for relevant results to use in a response.\nLearn more about the [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).\n'),
  "top_logprobs": zod.number().min(createChatCompletionBodyTopLogprobsMinFour).max(createChatCompletionBodyTopLogprobsMaxFour).nullish().describe('An integer between 0 and 20 specifying the number of most likely tokens to\nreturn at each token position, each with an associated log probability.\n`logprobs` must be set to `true` if this parameter is used.\n'),
  "response_format": zod.discriminatedUnion('type', [zod.object({
  "type": zod.enum(['text']).describe('The type of response format being defined. Always `text`.')
}).describe('Default response format. Used to generate text responses.\n'),zod.object({
  "type": zod.enum(['json_schema']).describe('The type of response format being defined. Always `json_schema`.'),
  "json_schema": zod.object({
  "description": zod.string().optional().describe('A description of what the response format is for, used by the model to\ndetermine how to respond in the format.\n'),
  "name": zod.string().describe('The name of the response format. Must be a-z, A-Z, 0-9, or contain\nunderscores and dashes, with a maximum length of 64.\n'),
  "schema": zod.record(zod.string(), zod.any()).optional().describe('The schema for the response format, described as a JSON Schema object.\nLearn how to build JSON schemas [here](https://json-schema.org/).\n'),
  "strict": zod.boolean().optional().describe('Whether to enable strict schema adherence when generating the output.\nIf set to true, the model will always follow the exact schema defined\nin the `schema` field. Only a subset of JSON Schema is supported when\n`strict` is `true`. To learn more, read the [Structured Outputs\nguide](https://platform.openai.com/docs/guides/structured-outputs).\n').or(zod.null()).optional()
}).describe('Structured Outputs configuration options, including a JSON Schema.\n')
}).describe('JSON Schema response format. Used to generate structured JSON responses.\nLearn more about [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs).\n'),zod.object({
  "type": zod.enum(['json_object']).describe('The type of response format being defined. Always `json_object`.')
}).describe('JSON object response format. An older method of generating JSON responses.\nUsing `json_schema` is recommended for models that support it. Note that the\nmodel will not generate JSON without a system or user message instructing it\nto do so.\n')]).optional().describe('An object specifying the format that the model must output.\n\nSetting to `{ \"type\": \"json_schema\", \"json_schema\": {...} }` enables\nStructured Outputs which ensures the model will match your supplied JSON\nschema. Learn more in the [Structured Outputs\nguide](https://platform.openai.com/docs/guides/structured-outputs).\n\nSetting to `{ \"type\": \"json_object\" }` enables the older JSON mode, which\nensures the message the model generates is valid JSON. Using `json_schema`\nis preferred for models that support it.\n'),
  "audio": zod.object({
  "voice": zod.string().or(zod.enum(['alloy', 'ash', 'ballad', 'coral', 'echo', 'sage', 'shimmer', 'verse', 'marin', 'cedar'])),
  "format": zod.enum(['wav', 'aac', 'mp3', 'flac', 'opus', 'pcm16']).describe('Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,\n`opus`, or `pcm16`.\n')
}).nullish().describe('Parameters for audio output. Required when audio output is requested with\n`modalities: [\"audio\"]`. [Learn more](https://platform.openai.com/docs/guides/audio).\n'),
  "store": zod.boolean().nullish().describe('Whether or not to store the output of this chat completion request for\nuse in our [model distillation](https://platform.openai.com/docs/guides/distillation) or\n[evals](https://platform.openai.com/docs/guides/evals) products.\n\nSupports text and image inputs. Note: image inputs over 8MB will be dropped.\n'),
  "stream": zod.boolean().nullish().describe('If set to true, the model response data will be streamed to the client\nas it is generated using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format).\nSee the [Streaming section below](https://platform.openai.com/docs/api-reference/chat/streaming)\nfor more information, along with the [streaming responses](https://platform.openai.com/docs/guides/streaming-responses)\nguide for more information on how to handle the streaming events.\n'),
  "stop": zod.string().optional().or(zod.array(zod.string()).min(1).max(createChatCompletionBodyStopMaxTwo)).nullish().describe('Not supported with latest reasoning models `o3` and `o4-mini`.\n\nUp to 4 sequences where the API will stop generating further tokens. The\nreturned text will not contain the stop sequence.\n'),
  "logit_bias": zod.record(zod.string(), zod.number()).nullish().describe('Modify the likelihood of specified tokens appearing in the completion.\n\nAccepts a JSON object that maps tokens (specified by their token ID in the\ntokenizer) to an associated bias value from -100 to 100. Mathematically,\nthe bias is added to the logits generated by the model prior to sampling.\nThe exact effect will vary per model, but values between -1 and 1 should\ndecrease or increase likelihood of selection; values like -100 or 100\nshould result in a ban or exclusive selection of the relevant token.\n'),
  "logprobs": zod.boolean().nullish().describe('Whether to return log probabilities of the output tokens or not. If true,\nreturns the log probabilities of each output token returned in the\n`content` of `message`.\n'),
  "max_tokens": zod.number().nullish().describe('The maximum number of [tokens](/tokenizer) that can be generated in the\nchat completion. This value can be used to control\n[costs](https://openai.com/api/pricing/) for text generated via API.\n\nThis value is now deprecated in favor of `max_completion_tokens`, and is\nnot compatible with [o-series models](https://platform.openai.com/docs/guides/reasoning).\n'),
  "n": zod.number().min(1).max(createChatCompletionBodyNMax).optional().describe('How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.'),
  "prediction": zod.discriminatedUnion('type', [zod.object({
  "type": zod.enum(['content']).describe('The type of the predicted content you want to provide. This type is\ncurrently always `content`.\n'),
  "content": zod.string().describe('The content used for a Predicted Output. This is often the\ntext of a file you are regenerating with minor changes.\n').or(zod.array(zod.object({
  "type": zod.enum(['text']).describe('The type of the content part.'),
  "text": zod.string().describe('The text content.')
}).describe('Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).\n')).min(1).describe('An array of content parts with a defined type. Supported options differ based on the [model](https://platform.openai.com/docs/models) being used to generate the response. Can contain text inputs.')).describe('The content that should be matched when generating a model response.\nIf generated tokens would match this content, the entire model response\ncan be returned much more quickly.\n')
}).describe('Static predicted output content, such as the content of a text file that is\nbeing regenerated.\n')]).nullish().describe('Configuration for a [Predicted Output](https://platform.openai.com/docs/guides/predicted-outputs),\nwhich can greatly improve response times when large parts of the model\nresponse are known ahead of time. This is most common when you are\nregenerating a file with only minor changes to most of the content.\n'),
  "seed": zod.number().min(createChatCompletionBodySeedMin).max(createChatCompletionBodySeedMax).nullish().describe('This feature is in Beta.\nIf specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.\nDeterminism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.\n'),
  "stream_options": zod.object({
  "include_usage": zod.boolean().optional().describe('If set, an additional chunk will be streamed before the `data: [DONE]`\nmessage. The `usage` field on this chunk shows the token usage statistics\nfor the entire request, and the `choices` field will always be an empty\narray.\n\nAll other chunks will also include a `usage` field, but with a null\nvalue. **NOTE:** If the stream is interrupted, you may not receive the\nfinal usage chunk which contains the total token usage for the request.\n'),
  "include_obfuscation": zod.boolean().optional().describe('When true, stream obfuscation will be enabled. Stream obfuscation adds\nrandom characters to an `obfuscation` field on streaming delta events to\nnormalize payload sizes as a mitigation to certain side-channel attacks.\nThese obfuscation fields are included by default, but add a small amount\nof overhead to the data stream. You can set `include_obfuscation` to\nfalse to optimize for bandwidth if you trust the network links between\nyour application and the OpenAI API.\n')
}).describe('Options for streaming response. Only set this when you set `stream: true`.\n').or(zod.null()).optional(),
  "tools": zod.array(zod.discriminatedUnion('type', [zod.object({
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "description": zod.string().optional().describe('A description of what the function does, used by the model to choose when and how to call the function.'),
  "name": zod.string().describe('The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.'),
  "parameters": zod.record(zod.string(), zod.any()).optional().describe('The parameters the functions accepts, described as a JSON Schema object. See the [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.\n\nOmitting `parameters` defines a function with an empty parameter list.'),
  "strict": zod.boolean().optional().describe('Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Learn more about Structured Outputs in the [function calling guide](https://platform.openai.com/docs/guides/function-calling).').or(zod.null()).optional()
})
}).describe('A function tool that can be used to generate a response.\n'),zod.object({
  "type": zod.enum(['custom']).describe('The type of the custom tool. Always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool, used to identify it in tool calls.'),
  "description": zod.string().optional().describe('Optional description of the custom tool, used to provide more context.\n'),
  "format": zod.discriminatedUnion('type', [zod.object({
  "type": zod.enum(['text']).describe('Unconstrained text format. Always `text`.')
}).describe('Unconstrained free-form text.'),zod.object({
  "type": zod.enum(['grammar']).describe('Grammar format. Always `grammar`.'),
  "grammar": zod.object({
  "definition": zod.string().describe('The grammar definition.'),
  "syntax": zod.enum(['lark', 'regex']).describe('The syntax of the grammar definition. One of `lark` or `regex`.')
}).describe('Your chosen grammar.')
}).describe('A grammar defined by the user.')]).optional().describe('The input format for the custom tool. Default is unconstrained text.\n')
}).describe('Properties of the custom tool.\n')
}).describe('A custom tool that processes input using a specified format.\n')])).optional().describe('A list of tools the model may call. You can provide either\n[custom tools](https://platform.openai.com/docs/guides/function-calling#custom-tools) or\n[function tools](https://platform.openai.com/docs/guides/function-calling).\n'),
  "tool_choice": zod.enum(['none', 'auto', 'required']).describe('`none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools.\n').or(zod.object({
  "type": zod.enum(['allowed_tools']).describe('Allowed tool configuration type. Always `allowed_tools`.'),
  "allowed_tools": zod.object({
  "mode": zod.enum(['auto', 'required']).describe('Constrains the tools available to the model to a pre-defined set.\n\n`auto` allows the model to pick from among the allowed tools and generate a\nmessage.\n\n`required` requires the model to call one or more of the allowed tools.\n'),
  "tools": zod.array(zod.record(zod.string(), zod.any()).describe('A tool definition that the model should be allowed to call.\n')).describe('A list of tool definitions that the model should be allowed to call.\n\nFor the Chat Completions API, the list of tool definitions might look like:\n```json\n[\n  { \"type\": \"function\", \"function\": { \"name\": \"get_weather\" } },\n  { \"type\": \"function\", \"function\": { \"name\": \"get_time\" } }\n]\n```\n')
}).describe('Constrains the tools available to the model to a pre-defined set.\n')
}).describe('Constrains the tools available to the model to a pre-defined set.\n')).or(zod.object({
  "type": zod.enum(['function']).describe('For function calling, the type is always `function`.'),
  "function": zod.object({
  "name": zod.string().describe('The name of the function to call.')
})
}).describe('Specifies a tool the model should use. Use to force the model to call a specific function.')).or(zod.object({
  "type": zod.enum(['custom']).describe('For custom tool calling, the type is always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool to call.')
})
}).describe('Specifies a tool the model should use. Use to force the model to call a specific custom tool.')).optional().describe('Controls which (if any) tool is called by the model.\n`none` means the model will not call any tool and instead generates a message.\n`auto` means the model can pick between generating a message or calling one or more tools.\n`required` means the model must call one or more tools.\nSpecifying a particular tool via `{\"type\": \"function\", \"function\": {\"name\": \"my_function\"}}` forces the model to call that tool.\n\n`none` is the default when no tools are present. `auto` is the default if tools are present.\n'),
  "parallel_tool_calls": zod.boolean().optional().describe('Whether to enable [parallel function calling](https://platform.openai.com/docs/guides/function-calling#configuring-parallel-function-calling) during tool use.'),
  "function_call": zod.enum(['none', 'auto']).describe('`none` means the model will not call a function and instead generates a message. `auto` means the model can pick between generating a message or calling a function.\n').or(zod.object({
  "name": zod.string().describe('The name of the function to call.')
}).describe('Specifying a particular function via `{\"name\": \"my_function\"}` forces the model to call that function.\n')).optional().describe('Deprecated in favor of `tool_choice`.\n\nControls which (if any) function is called by the model.\n\n`none` means the model will not call a function and instead generates a\nmessage.\n\n`auto` means the model can pick between generating a message or calling a\nfunction.\n\nSpecifying a particular function via `{\"name\": \"my_function\"}` forces the\nmodel to call that function.\n\n`none` is the default when no functions are present. `auto` is the default\nif functions are present.\n'),
  "functions": zod.array(zod.object({
  "description": zod.string().optional().describe('A description of what the function does, used by the model to choose when and how to call the function.'),
  "name": zod.string().describe('The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.'),
  "parameters": zod.record(zod.string(), zod.any()).optional().describe('The parameters the functions accepts, described as a JSON Schema object. See the [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.\n\nOmitting `parameters` defines a function with an empty parameter list.')
})).min(1).max(createChatCompletionBodyFunctionsMax).optional().describe('Deprecated in favor of `tools`.\n\nA list of functions the model may generate JSON inputs for.\n')
}))

export const createChatCompletionResponseServiceTierDefaultOne = "auto";export const createChatCompletionResponseUsageCompletionTokensDefault = 0;export const createChatCompletionResponseUsagePromptTokensDefault = 0;export const createChatCompletionResponseUsageTotalTokensDefault = 0;export const createChatCompletionResponseUsageCompletionTokensDetailsAcceptedPredictionTokensDefault = 0;export const createChatCompletionResponseUsageCompletionTokensDetailsAudioTokensDefault = 0;export const createChatCompletionResponseUsageCompletionTokensDetailsReasoningTokensDefault = 0;export const createChatCompletionResponseUsageCompletionTokensDetailsRejectedPredictionTokensDefault = 0;export const createChatCompletionResponseUsagePromptTokensDetailsAudioTokensDefault = 0;export const createChatCompletionResponseUsagePromptTokensDetailsCachedTokensDefault = 0;

export const createChatCompletionResponse = zod.object({
  "id": zod.string().describe('A unique identifier for the chat completion.'),
  "choices": zod.array(zod.object({
  "finish_reason": zod.enum(['stop', 'length', 'tool_calls', 'content_filter', 'function_call']).describe('The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,\n`length` if the maximum number of tokens specified in the request was reached,\n`content_filter` if content was omitted due to a flag from our content filters,\n`tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.\n'),
  "index": zod.number().describe('The index of the choice in the list of choices.'),
  "message": zod.object({
  "content": zod.string().describe('The contents of the message.').or(zod.null()),
  "refusal": zod.string().describe('The refusal message generated by the model.').or(zod.null()),
  "tool_calls": zod.array(zod.discriminatedUnion('type', [zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "name": zod.string().describe('The name of the function to call.'),
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.')
}).describe('The function that the model called.')
}).describe('A call to a function tool created by the model.\n'),zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['custom']).describe('The type of the tool. Always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool to call.'),
  "input": zod.string().describe('The input for the custom tool call generated by the model.')
}).describe('The custom tool that the model called.')
}).describe('A call to a custom tool created by the model.\n')])).optional().describe('The tool calls generated by the model, such as function calls.'),
  "annotations": zod.array(zod.object({
  "type": zod.enum(['url_citation']).describe('The type of the URL citation. Always `url_citation`.'),
  "url_citation": zod.object({
  "end_index": zod.number().describe('The index of the last character of the URL citation in the message.'),
  "start_index": zod.number().describe('The index of the first character of the URL citation in the message.'),
  "url": zod.string().describe('The URL of the web resource.'),
  "title": zod.string().describe('The title of the web resource.')
}).describe('A URL citation when using web search.')
}).describe('A URL citation when using web search.\n')).optional().describe('Annotations for the message, when applicable, as when using the\n[web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).\n'),
  "role": zod.enum(['assistant']).describe('The role of the author of this message.'),
  "function_call": zod.object({
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.'),
  "name": zod.string().describe('The name of the function to call.')
}).optional().describe('Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.'),
  "audio": zod.object({
  "id": zod.string().describe('Unique identifier for this audio response.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when this audio response will\nno longer be accessible on the server for use in multi-turn\nconversations.\n'),
  "data": zod.string().describe('Base64 encoded audio bytes generated by the model, in the format\nspecified in the request.\n'),
  "transcript": zod.string().describe('Transcript of the audio generated by the model.')
}).describe('If the audio output modality is requested, this object contains data\nabout the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).\n').or(zod.null()).optional()
}).describe('A chat completion message generated by the model.'),
  "logprobs": zod.object({
  "content": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message content tokens with log probability information.').or(zod.null()),
  "refusal": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message refusal tokens with log probability information.').or(zod.null())
}).describe('Log probability information for the choice.').or(zod.null())
})).describe('A list of chat completion choices. Can be more than one if `n` is greater than 1.'),
  "created": zod.number().describe('The Unix timestamp (in seconds) of when the chat completion was created.'),
  "model": zod.string().describe('The model used for the chat completion.'),
  "service_tier": zod.enum(['auto', 'default', 'flex', 'scale', 'priority']).optional().describe('Specifies the processing type used for serving the request.\n  - If set to \'auto\', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use \'default\'.\n  - If set to \'default\', then the request will be processed with the standard pricing and performance for the selected model.\n  - If set to \'[flex](https://platform.openai.com/docs/guides/flex-processing)\' or \'[priority](https://openai.com/api-priority-processing/)\', then the request will be processed with the corresponding service tier.\n  - When not set, the default behavior is \'auto\'.\n\n  When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter.\n').or(zod.null()).optional(),
  "system_fingerprint": zod.string().optional().describe('This fingerprint represents the backend configuration that the model runs with.\n\nCan be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.\n'),
  "object": zod.enum(['chat.completion']).describe('The object type, which is always `chat.completion`.'),
  "usage": zod.object({
  "completion_tokens": zod.number().optional().describe('Number of tokens in the generated completion.'),
  "prompt_tokens": zod.number().optional().describe('Number of tokens in the prompt.'),
  "total_tokens": zod.number().optional().describe('Total number of tokens used in the request (prompt + completion).'),
  "completion_tokens_details": zod.object({
  "accepted_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that appeared in the completion.\n'),
  "audio_tokens": zod.number().optional().describe('Audio input tokens generated by the model.'),
  "reasoning_tokens": zod.number().optional().describe('Tokens generated by the model for reasoning.'),
  "rejected_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that did not appear in the completion. However, like\nreasoning tokens, these tokens are still counted in the total\ncompletion tokens for purposes of billing, output, and context window\nlimits.\n')
}).optional().describe('Breakdown of tokens used in a completion.'),
  "prompt_tokens_details": zod.object({
  "audio_tokens": zod.number().optional().describe('Audio input tokens present in the prompt.'),
  "cached_tokens": zod.number().optional().describe('Cached tokens present in the prompt.')
}).optional().describe('Breakdown of tokens used in the prompt.')
}).optional().describe('Usage statistics for the completion request.')
}).describe('Represents a chat completion response returned by model, based on the provided input.')

/**
 * Get a stored chat completion. Only Chat Completions that have been created
with the `store` parameter set to `true` will be returned.

 * @summary Get chat completion
 */
export const getChatCompletionParams = zod.object({
  "completion_id": zod.string().describe('The ID of the chat completion to retrieve.')
})

export const getChatCompletionResponseServiceTierDefaultOne = "auto";export const getChatCompletionResponseUsageCompletionTokensDefault = 0;export const getChatCompletionResponseUsagePromptTokensDefault = 0;export const getChatCompletionResponseUsageTotalTokensDefault = 0;export const getChatCompletionResponseUsageCompletionTokensDetailsAcceptedPredictionTokensDefault = 0;export const getChatCompletionResponseUsageCompletionTokensDetailsAudioTokensDefault = 0;export const getChatCompletionResponseUsageCompletionTokensDetailsReasoningTokensDefault = 0;export const getChatCompletionResponseUsageCompletionTokensDetailsRejectedPredictionTokensDefault = 0;export const getChatCompletionResponseUsagePromptTokensDetailsAudioTokensDefault = 0;export const getChatCompletionResponseUsagePromptTokensDetailsCachedTokensDefault = 0;

export const getChatCompletionResponse = zod.object({
  "id": zod.string().describe('A unique identifier for the chat completion.'),
  "choices": zod.array(zod.object({
  "finish_reason": zod.enum(['stop', 'length', 'tool_calls', 'content_filter', 'function_call']).describe('The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,\n`length` if the maximum number of tokens specified in the request was reached,\n`content_filter` if content was omitted due to a flag from our content filters,\n`tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.\n'),
  "index": zod.number().describe('The index of the choice in the list of choices.'),
  "message": zod.object({
  "content": zod.string().describe('The contents of the message.').or(zod.null()),
  "refusal": zod.string().describe('The refusal message generated by the model.').or(zod.null()),
  "tool_calls": zod.array(zod.discriminatedUnion('type', [zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "name": zod.string().describe('The name of the function to call.'),
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.')
}).describe('The function that the model called.')
}).describe('A call to a function tool created by the model.\n'),zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['custom']).describe('The type of the tool. Always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool to call.'),
  "input": zod.string().describe('The input for the custom tool call generated by the model.')
}).describe('The custom tool that the model called.')
}).describe('A call to a custom tool created by the model.\n')])).optional().describe('The tool calls generated by the model, such as function calls.'),
  "annotations": zod.array(zod.object({
  "type": zod.enum(['url_citation']).describe('The type of the URL citation. Always `url_citation`.'),
  "url_citation": zod.object({
  "end_index": zod.number().describe('The index of the last character of the URL citation in the message.'),
  "start_index": zod.number().describe('The index of the first character of the URL citation in the message.'),
  "url": zod.string().describe('The URL of the web resource.'),
  "title": zod.string().describe('The title of the web resource.')
}).describe('A URL citation when using web search.')
}).describe('A URL citation when using web search.\n')).optional().describe('Annotations for the message, when applicable, as when using the\n[web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).\n'),
  "role": zod.enum(['assistant']).describe('The role of the author of this message.'),
  "function_call": zod.object({
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.'),
  "name": zod.string().describe('The name of the function to call.')
}).optional().describe('Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.'),
  "audio": zod.object({
  "id": zod.string().describe('Unique identifier for this audio response.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when this audio response will\nno longer be accessible on the server for use in multi-turn\nconversations.\n'),
  "data": zod.string().describe('Base64 encoded audio bytes generated by the model, in the format\nspecified in the request.\n'),
  "transcript": zod.string().describe('Transcript of the audio generated by the model.')
}).describe('If the audio output modality is requested, this object contains data\nabout the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).\n').or(zod.null()).optional()
}).describe('A chat completion message generated by the model.'),
  "logprobs": zod.object({
  "content": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message content tokens with log probability information.').or(zod.null()),
  "refusal": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message refusal tokens with log probability information.').or(zod.null())
}).describe('Log probability information for the choice.').or(zod.null())
})).describe('A list of chat completion choices. Can be more than one if `n` is greater than 1.'),
  "created": zod.number().describe('The Unix timestamp (in seconds) of when the chat completion was created.'),
  "model": zod.string().describe('The model used for the chat completion.'),
  "service_tier": zod.enum(['auto', 'default', 'flex', 'scale', 'priority']).optional().describe('Specifies the processing type used for serving the request.\n  - If set to \'auto\', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use \'default\'.\n  - If set to \'default\', then the request will be processed with the standard pricing and performance for the selected model.\n  - If set to \'[flex](https://platform.openai.com/docs/guides/flex-processing)\' or \'[priority](https://openai.com/api-priority-processing/)\', then the request will be processed with the corresponding service tier.\n  - When not set, the default behavior is \'auto\'.\n\n  When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter.\n').or(zod.null()).optional(),
  "system_fingerprint": zod.string().optional().describe('This fingerprint represents the backend configuration that the model runs with.\n\nCan be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.\n'),
  "object": zod.enum(['chat.completion']).describe('The object type, which is always `chat.completion`.'),
  "usage": zod.object({
  "completion_tokens": zod.number().optional().describe('Number of tokens in the generated completion.'),
  "prompt_tokens": zod.number().optional().describe('Number of tokens in the prompt.'),
  "total_tokens": zod.number().optional().describe('Total number of tokens used in the request (prompt + completion).'),
  "completion_tokens_details": zod.object({
  "accepted_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that appeared in the completion.\n'),
  "audio_tokens": zod.number().optional().describe('Audio input tokens generated by the model.'),
  "reasoning_tokens": zod.number().optional().describe('Tokens generated by the model for reasoning.'),
  "rejected_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that did not appear in the completion. However, like\nreasoning tokens, these tokens are still counted in the total\ncompletion tokens for purposes of billing, output, and context window\nlimits.\n')
}).optional().describe('Breakdown of tokens used in a completion.'),
  "prompt_tokens_details": zod.object({
  "audio_tokens": zod.number().optional().describe('Audio input tokens present in the prompt.'),
  "cached_tokens": zod.number().optional().describe('Cached tokens present in the prompt.')
}).optional().describe('Breakdown of tokens used in the prompt.')
}).optional().describe('Usage statistics for the completion request.')
}).describe('Represents a chat completion response returned by model, based on the provided input.')

/**
 * Modify a stored chat completion. Only Chat Completions that have been
created with the `store` parameter set to `true` can be modified. Currently,
the only supported modification is to update the `metadata` field.

 * @summary Update chat completion
 */
export const updateChatCompletionParams = zod.object({
  "completion_id": zod.string().describe('The ID of the chat completion to update.')
})

export const updateChatCompletionBody = zod.object({
  "metadata": zod.record(zod.string(), zod.string()).describe('Set of 16 key-value pairs that can be attached to an object. This can be\nuseful for storing additional information about the object in a structured\nformat, and querying for objects via API or the dashboard.\n\nKeys are strings with a maximum length of 64 characters. Values are strings\nwith a maximum length of 512 characters.\n').or(zod.null())
})

export const updateChatCompletionResponseServiceTierDefaultOne = "auto";export const updateChatCompletionResponseUsageCompletionTokensDefault = 0;export const updateChatCompletionResponseUsagePromptTokensDefault = 0;export const updateChatCompletionResponseUsageTotalTokensDefault = 0;export const updateChatCompletionResponseUsageCompletionTokensDetailsAcceptedPredictionTokensDefault = 0;export const updateChatCompletionResponseUsageCompletionTokensDetailsAudioTokensDefault = 0;export const updateChatCompletionResponseUsageCompletionTokensDetailsReasoningTokensDefault = 0;export const updateChatCompletionResponseUsageCompletionTokensDetailsRejectedPredictionTokensDefault = 0;export const updateChatCompletionResponseUsagePromptTokensDetailsAudioTokensDefault = 0;export const updateChatCompletionResponseUsagePromptTokensDetailsCachedTokensDefault = 0;

export const updateChatCompletionResponse = zod.object({
  "id": zod.string().describe('A unique identifier for the chat completion.'),
  "choices": zod.array(zod.object({
  "finish_reason": zod.enum(['stop', 'length', 'tool_calls', 'content_filter', 'function_call']).describe('The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,\n`length` if the maximum number of tokens specified in the request was reached,\n`content_filter` if content was omitted due to a flag from our content filters,\n`tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.\n'),
  "index": zod.number().describe('The index of the choice in the list of choices.'),
  "message": zod.object({
  "content": zod.string().describe('The contents of the message.').or(zod.null()),
  "refusal": zod.string().describe('The refusal message generated by the model.').or(zod.null()),
  "tool_calls": zod.array(zod.discriminatedUnion('type', [zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "name": zod.string().describe('The name of the function to call.'),
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.')
}).describe('The function that the model called.')
}).describe('A call to a function tool created by the model.\n'),zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['custom']).describe('The type of the tool. Always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool to call.'),
  "input": zod.string().describe('The input for the custom tool call generated by the model.')
}).describe('The custom tool that the model called.')
}).describe('A call to a custom tool created by the model.\n')])).optional().describe('The tool calls generated by the model, such as function calls.'),
  "annotations": zod.array(zod.object({
  "type": zod.enum(['url_citation']).describe('The type of the URL citation. Always `url_citation`.'),
  "url_citation": zod.object({
  "end_index": zod.number().describe('The index of the last character of the URL citation in the message.'),
  "start_index": zod.number().describe('The index of the first character of the URL citation in the message.'),
  "url": zod.string().describe('The URL of the web resource.'),
  "title": zod.string().describe('The title of the web resource.')
}).describe('A URL citation when using web search.')
}).describe('A URL citation when using web search.\n')).optional().describe('Annotations for the message, when applicable, as when using the\n[web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).\n'),
  "role": zod.enum(['assistant']).describe('The role of the author of this message.'),
  "function_call": zod.object({
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.'),
  "name": zod.string().describe('The name of the function to call.')
}).optional().describe('Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.'),
  "audio": zod.object({
  "id": zod.string().describe('Unique identifier for this audio response.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when this audio response will\nno longer be accessible on the server for use in multi-turn\nconversations.\n'),
  "data": zod.string().describe('Base64 encoded audio bytes generated by the model, in the format\nspecified in the request.\n'),
  "transcript": zod.string().describe('Transcript of the audio generated by the model.')
}).describe('If the audio output modality is requested, this object contains data\nabout the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).\n').or(zod.null()).optional()
}).describe('A chat completion message generated by the model.'),
  "logprobs": zod.object({
  "content": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message content tokens with log probability information.').or(zod.null()),
  "refusal": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null()),
  "top_logprobs": zod.array(zod.object({
  "token": zod.string().describe('The token.'),
  "logprob": zod.number().describe('The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.'),
  "bytes": zod.array(zod.number()).describe('A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.').or(zod.null())
})).describe('List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.')
})).describe('A list of message refusal tokens with log probability information.').or(zod.null())
}).describe('Log probability information for the choice.').or(zod.null())
})).describe('A list of chat completion choices. Can be more than one if `n` is greater than 1.'),
  "created": zod.number().describe('The Unix timestamp (in seconds) of when the chat completion was created.'),
  "model": zod.string().describe('The model used for the chat completion.'),
  "service_tier": zod.enum(['auto', 'default', 'flex', 'scale', 'priority']).optional().describe('Specifies the processing type used for serving the request.\n  - If set to \'auto\', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use \'default\'.\n  - If set to \'default\', then the request will be processed with the standard pricing and performance for the selected model.\n  - If set to \'[flex](https://platform.openai.com/docs/guides/flex-processing)\' or \'[priority](https://openai.com/api-priority-processing/)\', then the request will be processed with the corresponding service tier.\n  - When not set, the default behavior is \'auto\'.\n\n  When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter.\n').or(zod.null()).optional(),
  "system_fingerprint": zod.string().optional().describe('This fingerprint represents the backend configuration that the model runs with.\n\nCan be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.\n'),
  "object": zod.enum(['chat.completion']).describe('The object type, which is always `chat.completion`.'),
  "usage": zod.object({
  "completion_tokens": zod.number().optional().describe('Number of tokens in the generated completion.'),
  "prompt_tokens": zod.number().optional().describe('Number of tokens in the prompt.'),
  "total_tokens": zod.number().optional().describe('Total number of tokens used in the request (prompt + completion).'),
  "completion_tokens_details": zod.object({
  "accepted_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that appeared in the completion.\n'),
  "audio_tokens": zod.number().optional().describe('Audio input tokens generated by the model.'),
  "reasoning_tokens": zod.number().optional().describe('Tokens generated by the model for reasoning.'),
  "rejected_prediction_tokens": zod.number().optional().describe('When using Predicted Outputs, the number of tokens in the\nprediction that did not appear in the completion. However, like\nreasoning tokens, these tokens are still counted in the total\ncompletion tokens for purposes of billing, output, and context window\nlimits.\n')
}).optional().describe('Breakdown of tokens used in a completion.'),
  "prompt_tokens_details": zod.object({
  "audio_tokens": zod.number().optional().describe('Audio input tokens present in the prompt.'),
  "cached_tokens": zod.number().optional().describe('Cached tokens present in the prompt.')
}).optional().describe('Breakdown of tokens used in the prompt.')
}).optional().describe('Usage statistics for the completion request.')
}).describe('Represents a chat completion response returned by model, based on the provided input.')

/**
 * Delete a stored chat completion. Only Chat Completions that have been
created with the `store` parameter set to `true` can be deleted.

 * @summary Delete chat completion
 */
export const deleteChatCompletionParams = zod.object({
  "completion_id": zod.string().describe('The ID of the chat completion to delete.')
})

export const deleteChatCompletionResponse = zod.object({
  "object": zod.enum(['chat.completion.deleted']).describe('The type of object being deleted.'),
  "id": zod.string().describe('The ID of the chat completion that was deleted.'),
  "deleted": zod.boolean().describe('Whether the chat completion was deleted.')
})

/**
 * Get the messages in a stored chat completion. Only Chat Completions that
have been created with the `store` parameter set to `true` will be
returned.

 * @summary Get chat messages
 */
export const getChatCompletionMessagesParams = zod.object({
  "completion_id": zod.string().describe('The ID of the chat completion to retrieve messages from.')
})

export const getChatCompletionMessagesQueryLimitDefault = 20;export const getChatCompletionMessagesQueryOrderDefault = "asc";

export const getChatCompletionMessagesQueryParams = zod.object({
  "after": zod.string().optional().describe('Identifier for the last message from the previous pagination request.'),
  "limit": zod.number().optional().describe('Number of messages to retrieve.'),
  "order": zod.enum(['asc', 'desc']).optional().describe('Sort order for messages by timestamp. Use `asc` for ascending order or `desc` for descending order. Defaults to `asc`.')
})

export const getChatCompletionMessagesResponseObjectDefault = "list";export const getChatCompletionMessagesResponseDataItemContentPartsItemImageUrlDetailDefault = "auto";

export const getChatCompletionMessagesResponse = zod.object({
  "object": zod.enum(['list']).optional().describe('The type of this object. It is always set to \"list\".\n'),
  "data": zod.array(zod.object({
  "content": zod.string().describe('The contents of the message.').or(zod.null()),
  "refusal": zod.string().describe('The refusal message generated by the model.').or(zod.null()),
  "tool_calls": zod.array(zod.discriminatedUnion('type', [zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "name": zod.string().describe('The name of the function to call.'),
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.')
}).describe('The function that the model called.')
}).describe('A call to a function tool created by the model.\n'),zod.object({
  "id": zod.string().describe('The ID of the tool call.'),
  "type": zod.enum(['custom']).describe('The type of the tool. Always `custom`.'),
  "custom": zod.object({
  "name": zod.string().describe('The name of the custom tool to call.'),
  "input": zod.string().describe('The input for the custom tool call generated by the model.')
}).describe('The custom tool that the model called.')
}).describe('A call to a custom tool created by the model.\n')])).optional().describe('The tool calls generated by the model, such as function calls.'),
  "annotations": zod.array(zod.object({
  "type": zod.enum(['url_citation']).describe('The type of the URL citation. Always `url_citation`.'),
  "url_citation": zod.object({
  "end_index": zod.number().describe('The index of the last character of the URL citation in the message.'),
  "start_index": zod.number().describe('The index of the first character of the URL citation in the message.'),
  "url": zod.string().describe('The URL of the web resource.'),
  "title": zod.string().describe('The title of the web resource.')
}).describe('A URL citation when using web search.')
}).describe('A URL citation when using web search.\n')).optional().describe('Annotations for the message, when applicable, as when using the\n[web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).\n'),
  "role": zod.enum(['assistant']).describe('The role of the author of this message.'),
  "function_call": zod.object({
  "arguments": zod.string().describe('The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.'),
  "name": zod.string().describe('The name of the function to call.')
}).optional().describe('Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.'),
  "audio": zod.object({
  "id": zod.string().describe('Unique identifier for this audio response.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when this audio response will\nno longer be accessible on the server for use in multi-turn\nconversations.\n'),
  "data": zod.string().describe('Base64 encoded audio bytes generated by the model, in the format\nspecified in the request.\n'),
  "transcript": zod.string().describe('Transcript of the audio generated by the model.')
}).describe('If the audio output modality is requested, this object contains data\nabout the audio response from the model. [Learn more](https://platform.openai.com/docs/guides/audio).\n').or(zod.null()).optional()
}).describe('A chat completion message generated by the model.').and(zod.object({
  "id": zod.string().describe('The identifier of the chat message.'),
  "content_parts": zod.array(zod.object({
  "type": zod.enum(['text']).describe('The type of the content part.'),
  "text": zod.string().describe('The text content.')
}).describe('Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).\n').or(zod.object({
  "type": zod.enum(['image_url']).describe('The type of the content part.'),
  "image_url": zod.object({
  "url": zod.string().url().describe('Either a URL of the image or the base64 encoded image data.'),
  "detail": zod.enum(['auto', 'low', 'high']).optional().describe('Specifies the detail level of the image. Learn more in the [Vision guide](https://platform.openai.com/docs/guides/vision#low-or-high-fidelity-image-understanding).')
})
}).describe('Learn about [image inputs](https://platform.openai.com/docs/guides/vision).\n'))).describe('If a content parts array was provided, this is an array of `text` and `image_url` parts.\nOtherwise, null.\n').or(zod.null()).optional()
}))).describe('An array of chat completion message objects.\n'),
  "first_id": zod.string().describe('The identifier of the first chat message in the data array.'),
  "last_id": zod.string().describe('The identifier of the last chat message in the data array.'),
  "has_more": zod.boolean().describe('Indicates whether there are more chat messages available.')
}).describe('An object representing a list of chat completion messages.\n')

