/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { DeleteModelResponse, ListModelsResponse, Model } from '.././schema';
export declare const getModels: () => {
    listModels: <TData = axios.AxiosResponse<ListModelsResponse, any>>(options?: AxiosRequestConfig) => Promise<TData>;
    retrieveModel: <TData = axios.AxiosResponse<Model, any>>(model: string, options?: AxiosRequestConfig) => Promise<TData>;
    deleteModel: <TData = axios.AxiosResponse<DeleteModelResponse, any>>(model: string, options?: AxiosRequestConfig) => Promise<TData>;
};
export type ListModelsResult = AxiosResponse<ListModelsResponse>;
export type RetrieveModelResult = AxiosResponse<Model>;
export type DeleteModelResult = AxiosResponse<DeleteModelResponse>;
//# sourceMappingURL=models.d.ts.map