/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteModelResponse,
  ListModelsResponse,
  Model
} from '.././schema';




  export const getModels = () => {
/**
 * Lists the currently available models, and provides basic information about each one such as the owner and availability.
 * @summary List models
 */
const listModels = <TData = AxiosResponse<ListModelsResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/models`,options
    );
  }
/**
 * Retrieves a model instance, providing basic information about the model such as the owner and permissioning.
 * @summary Retrieve model
 */
const retrieveModel = <TData = AxiosResponse<Model>>(
    model: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/models/${model}`,options
    );
  }
/**
 * Delete a fine-tuned model. You must have the Owner role in your organization to delete a model.
 * @summary Delete a fine-tuned model
 */
const deleteModel = <TData = AxiosResponse<DeleteModelResponse>>(
    model: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/models/${model}`,options
    );
  }
return {listModels,retrieveModel,deleteModel}};
export type ListModelsResult = AxiosResponse<ListModelsResponse>
export type RetrieveModelResult = AxiosResponse<Model>
export type DeleteModelResult = AxiosResponse<DeleteModelResponse>
