/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * Create a video
 * @summary Create video
 */
export const createVideoBodyPromptMax = 32000;


export const createVideoBody = zod.object({
  "model": zod.enum(['sora-2', 'sora-2-pro']).optional(),
  "prompt": zod.string().min(1).max(createVideoBodyPromptMax).describe('Text prompt that describes the video to generate.'),
  "input_reference": zod.instanceof(File).optional().describe('Optional image reference that guides generation.'),
  "seconds": zod.enum(['4', '8', '12']).optional(),
  "size": zod.enum(['720x1280', '1280x720', '1024x1792', '1792x1024']).optional()
}).describe('Parameters for creating a new video generation job.')

export const createVideoResponseObjectDefault = "video";

export const createVideoResponse = zod.object({
  "id": zod.string().describe('Unique identifier for the video job.'),
  "object": zod.enum(['video']).optional().describe('The object type, which is always `video`.'),
  "model": zod.enum(['sora-2', 'sora-2-pro']),
  "status": zod.enum(['queued', 'in_progress', 'completed', 'failed']),
  "progress": zod.number().describe('Approximate completion percentage for the generation task.'),
  "created_at": zod.number().describe('Unix timestamp (seconds) for when the job was created.'),
  "completed_at": zod.number().describe('Unix timestamp (seconds) for when the job completed, if finished.').or(zod.null()),
  "expires_at": zod.number().describe('Unix timestamp (seconds) for when the downloadable assets expire, if set.').or(zod.null()),
  "size": zod.enum(['720x1280', '1280x720', '1024x1792', '1792x1024']),
  "seconds": zod.enum(['4', '8', '12']),
  "remixed_from_video_id": zod.string().describe('Identifier of the source video if this video is a remix.').or(zod.null()),
  "error": zod.object({
  "code": zod.string(),
  "message": zod.string()
}).or(zod.null())
}).describe('Structured information describing a generated video job.')

/**
 * List videos
 * @summary List videos
 */
export const listVideosQueryLimitMin = 0;

export const listVideosQueryLimitMax = 100;


export const listVideosQueryParams = zod.object({
  "limit": zod.number().min(listVideosQueryLimitMin).max(listVideosQueryLimitMax).optional().describe('Number of items to retrieve'),
  "order": zod.enum(['asc', 'desc']).optional().describe('Sort order of results by timestamp. Use `asc` for ascending order or `desc` for descending order.'),
  "after": zod.string().optional().describe('Identifier for the last item from the previous pagination request')
})

export const listVideosResponseObjectDefault = "list";export const listVideosResponseDataItemObjectDefault = "video";

export const listVideosResponse = zod.object({
  "object": zod.any().optional().describe('The type of object returned, must be `list`.'),
  "data": zod.array(zod.object({
  "id": zod.string().describe('Unique identifier for the video job.'),
  "object": zod.enum(['video']).optional().describe('The object type, which is always `video`.'),
  "model": zod.enum(['sora-2', 'sora-2-pro']),
  "status": zod.enum(['queued', 'in_progress', 'completed', 'failed']),
  "progress": zod.number().describe('Approximate completion percentage for the generation task.'),
  "created_at": zod.number().describe('Unix timestamp (seconds) for when the job was created.'),
  "completed_at": zod.number().describe('Unix timestamp (seconds) for when the job completed, if finished.').or(zod.null()),
  "expires_at": zod.number().describe('Unix timestamp (seconds) for when the downloadable assets expire, if set.').or(zod.null()),
  "size": zod.enum(['720x1280', '1280x720', '1024x1792', '1792x1024']),
  "seconds": zod.enum(['4', '8', '12']),
  "remixed_from_video_id": zod.string().describe('Identifier of the source video if this video is a remix.').or(zod.null()),
  "error": zod.object({
  "code": zod.string(),
  "message": zod.string()
}).or(zod.null())
}).describe('Structured information describing a generated video job.')).describe('A list of items'),
  "first_id": zod.string().describe('The ID of the first item in the list.').or(zod.null()),
  "last_id": zod.string().describe('The ID of the last item in the list.').or(zod.null()),
  "has_more": zod.boolean().describe('Whether there are more items available.')
})

/**
 * Retrieve a video
 * @summary Retrieve video
 */
export const getVideoParams = zod.object({
  "video_id": zod.string().describe('The identifier of the video to retrieve.')
})

export const getVideoResponseObjectDefault = "video";

export const getVideoResponse = zod.object({
  "id": zod.string().describe('Unique identifier for the video job.'),
  "object": zod.enum(['video']).optional().describe('The object type, which is always `video`.'),
  "model": zod.enum(['sora-2', 'sora-2-pro']),
  "status": zod.enum(['queued', 'in_progress', 'completed', 'failed']),
  "progress": zod.number().describe('Approximate completion percentage for the generation task.'),
  "created_at": zod.number().describe('Unix timestamp (seconds) for when the job was created.'),
  "completed_at": zod.number().describe('Unix timestamp (seconds) for when the job completed, if finished.').or(zod.null()),
  "expires_at": zod.number().describe('Unix timestamp (seconds) for when the downloadable assets expire, if set.').or(zod.null()),
  "size": zod.enum(['720x1280', '1280x720', '1024x1792', '1792x1024']),
  "seconds": zod.enum(['4', '8', '12']),
  "remixed_from_video_id": zod.string().describe('Identifier of the source video if this video is a remix.').or(zod.null()),
  "error": zod.object({
  "code": zod.string(),
  "message": zod.string()
}).or(zod.null())
}).describe('Structured information describing a generated video job.')

/**
 * Delete a video
 * @summary Delete video
 */
export const deleteVideoParams = zod.object({
  "video_id": zod.string().describe('The identifier of the video to delete.')
})

export const deleteVideoResponseObjectDefault = "video.deleted";

export const deleteVideoResponse = zod.object({
  "object": zod.enum(['video.deleted']).optional().describe('The object type that signals the deletion response.'),
  "deleted": zod.boolean().describe('Indicates that the video resource was deleted.'),
  "id": zod.string().describe('Identifier of the deleted video.')
}).describe('Confirmation payload returned after deleting a video.')

/**
 * Download video content
 * @summary Retrieve video content
 */
export const retrieveVideoContentParams = zod.object({
  "video_id": zod.string().describe('The identifier of the video whose media to download.')
})

export const retrieveVideoContentQueryParams = zod.object({
  "variant": zod.enum(['video', 'thumbnail', 'spritesheet']).optional().describe('Which downloadable asset to return. Defaults to the MP4 video.')
})

export const retrieveVideoContentResponse = zod.string()

/**
 * Create a video remix
 * @summary Remix video
 */
export const createVideoRemixParams = zod.object({
  "video_id": zod.string().describe('The identifier of the completed video to remix.')
})

export const createVideoRemixBodyPromptMax = 32000;


export const createVideoRemixBody = zod.object({
  "prompt": zod.string().min(1).max(createVideoRemixBodyPromptMax).describe('Updated text prompt that directs the remix generation.')
}).describe('Parameters for remixing an existing generated video.')

export const createVideoRemixResponseObjectDefault = "video";

export const createVideoRemixResponse = zod.object({
  "id": zod.string().describe('Unique identifier for the video job.'),
  "object": zod.enum(['video']).optional().describe('The object type, which is always `video`.'),
  "model": zod.enum(['sora-2', 'sora-2-pro']),
  "status": zod.enum(['queued', 'in_progress', 'completed', 'failed']),
  "progress": zod.number().describe('Approximate completion percentage for the generation task.'),
  "created_at": zod.number().describe('Unix timestamp (seconds) for when the job was created.'),
  "completed_at": zod.number().describe('Unix timestamp (seconds) for when the job completed, if finished.').or(zod.null()),
  "expires_at": zod.number().describe('Unix timestamp (seconds) for when the downloadable assets expire, if set.').or(zod.null()),
  "size": zod.enum(['720x1280', '1280x720', '1024x1792', '1792x1024']),
  "seconds": zod.enum(['4', '8', '12']),
  "remixed_from_video_id": zod.string().describe('Identifier of the source video if this video is a remix.').or(zod.null()),
  "error": zod.object({
  "code": zod.string(),
  "message": zod.string()
}).or(zod.null())
}).describe('Structured information describing a generated video job.')

