/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { ListProjectApiKeysParams, ListProjectServiceAccountsParams, ListProjectUsersParams, ListProjectsParams, Project, ProjectApiKey, ProjectApiKeyDeleteResponse, ProjectApiKeyListResponse, ProjectCreateRequest, ProjectListResponse, ProjectServiceAccount, ProjectServiceAccountCreateRequest, ProjectServiceAccountCreateResponse, ProjectServiceAccountDeleteResponse, ProjectServiceAccountListResponse, ProjectUpdateRequest, ProjectUser, ProjectUserCreateRequest, ProjectUserDeleteResponse, ProjectUserListResponse, ProjectUserUpdateRequest } from '.././schema';
export declare const getProjects: () => {
    listProjects: <TData = axios.AxiosResponse<ProjectListResponse, any>>(params?: ListProjectsParams, options?: AxiosRequestConfig) => Promise<TData>;
    createProject: <TData = axios.AxiosResponse<Project, any>>(projectCreateRequest: ProjectCreateRequest, options?: AxiosRequestConfig) => Promise<TData>;
    retrieveProject: <TData = axios.AxiosResponse<Project, any>>(projectId: string, options?: AxiosRequestConfig) => Promise<TData>;
    modifyProject: <TData = axios.AxiosResponse<Project, any>>(projectId: string, projectUpdateRequest: ProjectUpdateRequest, options?: AxiosRequestConfig) => Promise<TData>;
    archiveProject: <TData = axios.AxiosResponse<Project, any>>(projectId: string, options?: AxiosRequestConfig) => Promise<TData>;
    listProjectUsers: <TData = axios.AxiosResponse<ProjectUserListResponse, any>>(projectId: string, params?: ListProjectUsersParams, options?: AxiosRequestConfig) => Promise<TData>;
    createProjectUser: <TData = axios.AxiosResponse<ProjectUser, any>>(projectId: string, projectUserCreateRequest: ProjectUserCreateRequest, options?: AxiosRequestConfig) => Promise<TData>;
    retrieveProjectUser: <TData = axios.AxiosResponse<ProjectUser, any>>(projectId: string, userId: string, options?: AxiosRequestConfig) => Promise<TData>;
    modifyProjectUser: <TData = axios.AxiosResponse<ProjectUser, any>>(projectId: string, userId: string, projectUserUpdateRequest: ProjectUserUpdateRequest, options?: AxiosRequestConfig) => Promise<TData>;
    deleteProjectUser: <TData = axios.AxiosResponse<ProjectUserDeleteResponse, any>>(projectId: string, userId: string, options?: AxiosRequestConfig) => Promise<TData>;
    listProjectServiceAccounts: <TData = axios.AxiosResponse<ProjectServiceAccountListResponse, any>>(projectId: string, params?: ListProjectServiceAccountsParams, options?: AxiosRequestConfig) => Promise<TData>;
    createProjectServiceAccount: <TData = axios.AxiosResponse<ProjectServiceAccountCreateResponse, any>>(projectId: string, projectServiceAccountCreateRequest: ProjectServiceAccountCreateRequest, options?: AxiosRequestConfig) => Promise<TData>;
    retrieveProjectServiceAccount: <TData = axios.AxiosResponse<ProjectServiceAccount, any>>(projectId: string, serviceAccountId: string, options?: AxiosRequestConfig) => Promise<TData>;
    deleteProjectServiceAccount: <TData = axios.AxiosResponse<ProjectServiceAccountDeleteResponse, any>>(projectId: string, serviceAccountId: string, options?: AxiosRequestConfig) => Promise<TData>;
    listProjectApiKeys: <TData = axios.AxiosResponse<ProjectApiKeyListResponse, any>>(projectId: string, params?: ListProjectApiKeysParams, options?: AxiosRequestConfig) => Promise<TData>;
    retrieveProjectApiKey: <TData = axios.AxiosResponse<ProjectApiKey, any>>(projectId: string, keyId: string, options?: AxiosRequestConfig) => Promise<TData>;
    deleteProjectApiKey: <TData = axios.AxiosResponse<ProjectApiKeyDeleteResponse, any>>(projectId: string, keyId: string, options?: AxiosRequestConfig) => Promise<TData>;
};
export type ListProjectsResult = AxiosResponse<ProjectListResponse>;
export type CreateProjectResult = AxiosResponse<Project>;
export type RetrieveProjectResult = AxiosResponse<Project>;
export type ModifyProjectResult = AxiosResponse<Project>;
export type ArchiveProjectResult = AxiosResponse<Project>;
export type ListProjectUsersResult = AxiosResponse<ProjectUserListResponse>;
export type CreateProjectUserResult = AxiosResponse<ProjectUser>;
export type RetrieveProjectUserResult = AxiosResponse<ProjectUser>;
export type ModifyProjectUserResult = AxiosResponse<ProjectUser>;
export type DeleteProjectUserResult = AxiosResponse<ProjectUserDeleteResponse>;
export type ListProjectServiceAccountsResult = AxiosResponse<ProjectServiceAccountListResponse>;
export type CreateProjectServiceAccountResult = AxiosResponse<ProjectServiceAccountCreateResponse>;
export type RetrieveProjectServiceAccountResult = AxiosResponse<ProjectServiceAccount>;
export type DeleteProjectServiceAccountResult = AxiosResponse<ProjectServiceAccountDeleteResponse>;
export type ListProjectApiKeysResult = AxiosResponse<ProjectApiKeyListResponse>;
export type RetrieveProjectApiKeyResult = AxiosResponse<ProjectApiKey>;
export type DeleteProjectApiKeyResult = AxiosResponse<ProjectApiKeyDeleteResponse>;
//# sourceMappingURL=projects.d.ts.map