/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ListProjectApiKeysParams,
  ListProjectRateLimitsParams,
  ListProjectServiceAccountsParams,
  ListProjectUsersParams,
  ListProjectsParams,
  Project,
  ProjectApiKey,
  ProjectApiKeyDeleteResponse,
  ProjectApiKeyListResponse,
  ProjectCreateRequest,
  ProjectListResponse,
  ProjectRateLimit,
  ProjectRateLimitListResponse,
  ProjectRateLimitUpdateRequest,
  ProjectServiceAccount,
  ProjectServiceAccountCreateRequest,
  ProjectServiceAccountCreateResponse,
  ProjectServiceAccountDeleteResponse,
  ProjectServiceAccountListResponse,
  ProjectUpdateRequest,
  ProjectUser,
  ProjectUserCreateRequest,
  ProjectUserDeleteResponse,
  ProjectUserListResponse,
  ProjectUserUpdateRequest
} from '.././schema';




  export const getProjects = () => {
/**
 * Returns a list of projects.
 * @summary List projects
 */
const listProjects = <TData = AxiosResponse<ProjectListResponse>>(
    params?: ListProjectsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new project in the organization. Projects can be created and archived, but cannot be deleted.
 * @summary Create project
 */
const createProject = <TData = AxiosResponse<Project>>(
    projectCreateRequest: ProjectCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects`,
      projectCreateRequest,options
    );
  }
/**
 * Retrieves a project.
 * @summary Retrieve project
 */
const retrieveProject = <TData = AxiosResponse<Project>>(
    projectId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}`,options
    );
  }
/**
 * Modifies a project in the organization.
 * @summary Modify project
 */
const modifyProject = <TData = AxiosResponse<Project>>(
    projectId: string,
    projectUpdateRequest: ProjectUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}`,
      projectUpdateRequest,options
    );
  }
/**
 * Returns a list of API keys in the project.
 * @summary List project API keys
 */
const listProjectApiKeys = <TData = AxiosResponse<ProjectApiKeyListResponse>>(
    projectId: string,
    params?: ListProjectApiKeysParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/api_keys`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieves an API key in the project.
 * @summary Retrieve project API key
 */
const retrieveProjectApiKey = <TData = AxiosResponse<ProjectApiKey>>(
    projectId: string,
    keyId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/api_keys/${keyId}`,options
    );
  }
/**
 * Deletes an API key from the project.
 * @summary Delete project API key
 */
const deleteProjectApiKey = <TData = AxiosResponse<ProjectApiKeyDeleteResponse>>(
    projectId: string,
    keyId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/organization/projects/${projectId}/api_keys/${keyId}`,options
    );
  }
/**
 * Archives a project in the organization. Archived projects cannot be used or updated.
 * @summary Archive project
 */
const archiveProject = <TData = AxiosResponse<Project>>(
    projectId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}/archive`,undefined,options
    );
  }
/**
 * Returns the rate limits per model for a project.
 * @summary List project rate limits
 */
const listProjectRateLimits = <TData = AxiosResponse<ProjectRateLimitListResponse>>(
    projectId: string,
    params?: ListProjectRateLimitsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/rate_limits`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Updates a project rate limit.
 * @summary Modify project rate limit
 */
const updateProjectRateLimits = <TData = AxiosResponse<ProjectRateLimit>>(
    projectId: string,
    rateLimitId: string,
    projectRateLimitUpdateRequest: ProjectRateLimitUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}/rate_limits/${rateLimitId}`,
      projectRateLimitUpdateRequest,options
    );
  }
/**
 * Returns a list of service accounts in the project.
 * @summary List project service accounts
 */
const listProjectServiceAccounts = <TData = AxiosResponse<ProjectServiceAccountListResponse>>(
    projectId: string,
    params?: ListProjectServiceAccountsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/service_accounts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Creates a new service account in the project. This also returns an unredacted API key for the service account.
 * @summary Create project service account
 */
const createProjectServiceAccount = <TData = AxiosResponse<ProjectServiceAccountCreateResponse>>(
    projectId: string,
    projectServiceAccountCreateRequest: ProjectServiceAccountCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}/service_accounts`,
      projectServiceAccountCreateRequest,options
    );
  }
/**
 * Retrieves a service account in the project.
 * @summary Retrieve project service account
 */
const retrieveProjectServiceAccount = <TData = AxiosResponse<ProjectServiceAccount>>(
    projectId: string,
    serviceAccountId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/service_accounts/${serviceAccountId}`,options
    );
  }
/**
 * Deletes a service account from the project.
 * @summary Delete project service account
 */
const deleteProjectServiceAccount = <TData = AxiosResponse<ProjectServiceAccountDeleteResponse>>(
    projectId: string,
    serviceAccountId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/organization/projects/${projectId}/service_accounts/${serviceAccountId}`,options
    );
  }
/**
 * Returns a list of users in the project.
 * @summary List project users
 */
const listProjectUsers = <TData = AxiosResponse<ProjectUserListResponse>>(
    projectId: string,
    params?: ListProjectUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Adds a user to the project. Users must already be members of the organization to be added to a project.
 * @summary Create project user
 */
const createProjectUser = <TData = AxiosResponse<ProjectUser>>(
    projectId: string,
    projectUserCreateRequest: ProjectUserCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}/users`,
      projectUserCreateRequest,options
    );
  }
/**
 * Retrieves a user in the project.
 * @summary Retrieve project user
 */
const retrieveProjectUser = <TData = AxiosResponse<ProjectUser>>(
    projectId: string,
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/users/${userId}`,options
    );
  }
/**
 * Modifies a user's role in the project.
 * @summary Modify project user
 */
const modifyProjectUser = <TData = AxiosResponse<ProjectUser>>(
    projectId: string,
    userId: string,
    projectUserUpdateRequest: ProjectUserUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}/users/${userId}`,
      projectUserUpdateRequest,options
    );
  }
/**
 * Deletes a user from the project.
 * @summary Delete project user
 */
const deleteProjectUser = <TData = AxiosResponse<ProjectUserDeleteResponse>>(
    projectId: string,
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/organization/projects/${projectId}/users/${userId}`,options
    );
  }
return {listProjects,createProject,retrieveProject,modifyProject,listProjectApiKeys,retrieveProjectApiKey,deleteProjectApiKey,archiveProject,listProjectRateLimits,updateProjectRateLimits,listProjectServiceAccounts,createProjectServiceAccount,retrieveProjectServiceAccount,deleteProjectServiceAccount,listProjectUsers,createProjectUser,retrieveProjectUser,modifyProjectUser,deleteProjectUser}};
export type ListProjectsResult = AxiosResponse<ProjectListResponse>
export type CreateProjectResult = AxiosResponse<Project>
export type RetrieveProjectResult = AxiosResponse<Project>
export type ModifyProjectResult = AxiosResponse<Project>
export type ListProjectApiKeysResult = AxiosResponse<ProjectApiKeyListResponse>
export type RetrieveProjectApiKeyResult = AxiosResponse<ProjectApiKey>
export type DeleteProjectApiKeyResult = AxiosResponse<ProjectApiKeyDeleteResponse>
export type ArchiveProjectResult = AxiosResponse<Project>
export type ListProjectRateLimitsResult = AxiosResponse<ProjectRateLimitListResponse>
export type UpdateProjectRateLimitsResult = AxiosResponse<ProjectRateLimit>
export type ListProjectServiceAccountsResult = AxiosResponse<ProjectServiceAccountListResponse>
export type CreateProjectServiceAccountResult = AxiosResponse<ProjectServiceAccountCreateResponse>
export type RetrieveProjectServiceAccountResult = AxiosResponse<ProjectServiceAccount>
export type DeleteProjectServiceAccountResult = AxiosResponse<ProjectServiceAccountDeleteResponse>
export type ListProjectUsersResult = AxiosResponse<ProjectUserListResponse>
export type CreateProjectUserResult = AxiosResponse<ProjectUser>
export type RetrieveProjectUserResult = AxiosResponse<ProjectUser>
export type ModifyProjectUserResult = AxiosResponse<ProjectUser>
export type DeleteProjectUserResult = AxiosResponse<ProjectUserDeleteResponse>
