/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { AddUploadPartRequest, CompleteUploadRequest, CreateUploadRequest, Upload, UploadPart } from '.././schema';
export declare const getUploads: () => {
    createUpload: <TData = axios.AxiosResponse<Upload, any>>(createUploadRequest: CreateUploadRequest, options?: AxiosRequestConfig) => Promise<TData>;
    addUploadPart: <TData = axios.AxiosResponse<UploadPart, any>>(uploadId: string, addUploadPartRequest: AddUploadPartRequest, options?: AxiosRequestConfig) => Promise<TData>;
    completeUpload: <TData = axios.AxiosResponse<Upload, any>>(uploadId: string, completeUploadRequest: CompleteUploadRequest, options?: AxiosRequestConfig) => Promise<TData>;
    cancelUpload: <TData = axios.AxiosResponse<Upload, any>>(uploadId: string, options?: AxiosRequestConfig) => Promise<TData>;
};
export type CreateUploadResult = AxiosResponse<Upload>;
export type AddUploadPartResult = AxiosResponse<UploadPart>;
export type CompleteUploadResult = AxiosResponse<Upload>;
export type CancelUploadResult = AxiosResponse<Upload>;
//# sourceMappingURL=uploads.d.ts.map