/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateFileRequest,
  DeleteFileResponse,
  ListFilesParams,
  ListFilesResponse,
  OpenAIFile
} from '.././schema';




  export const getFiles = () => {
/**
 * Returns a list of files.
 * @summary List files
 */
const listFiles = <TData = AxiosResponse<ListFilesResponse>>(
    params?: ListFilesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/files`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Upload a file that can be used across various endpoints. Individual files can be up to 512 MB, and the size of all files uploaded by one organization can be up to 1 TB.

The Assistants API supports files up to 2 million tokens and of specific file types. See the [Assistants Tools guide](https://platform.openai.com/docs/assistants/tools) for details.

The Fine-tuning API only supports `.jsonl` files. The input also has certain required formats for fine-tuning [chat](https://platform.openai.com/docs/api-reference/fine-tuning/chat-input) or [completions](https://platform.openai.com/docs/api-reference/fine-tuning/completions-input) models.

The Batch API only supports `.jsonl` files up to 200 MB in size. The input also has a specific required [format](https://platform.openai.com/docs/api-reference/batch/request-input).

Please [contact us](https://help.openai.com/) if you need to increase these storage limits.

 * @summary Upload file
 */
const createFile = <TData = AxiosResponse<OpenAIFile>>(
    createFileRequest: CreateFileRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append('file', createFileRequest.file)
formData.append('purpose', createFileRequest.purpose)
if(createFileRequest.expires_after !== undefined) {
 formData.append('expires_after', JSON.stringify(createFileRequest.expires_after));
 }

    return axios.default.post(
      `/files`,
      formData,options
    );
  }
/**
 * Delete a file and remove it from all vector stores.
 * @summary Delete file
 */
const deleteFile = <TData = AxiosResponse<DeleteFileResponse>>(
    fileId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/files/${fileId}`,options
    );
  }
/**
 * Returns information about a specific file.
 * @summary Retrieve file
 */
const retrieveFile = <TData = AxiosResponse<OpenAIFile>>(
    fileId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/files/${fileId}`,options
    );
  }
/**
 * Returns the contents of the specified file.
 * @summary Retrieve file content
 */
const downloadFile = <TData = AxiosResponse<string>>(
    fileId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/files/${fileId}/content`,options
    );
  }
return {listFiles,createFile,deleteFile,retrieveFile,downloadFile}};
export type ListFilesResult = AxiosResponse<ListFilesResponse>
export type CreateFileResult = AxiosResponse<OpenAIFile>
export type DeleteFileResult = AxiosResponse<DeleteFileResponse>
export type RetrieveFileResult = AxiosResponse<OpenAIFile>
export type DownloadFileResult = AxiosResponse<string>
