/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { CreateFineTuningJobRequest, FineTuningJob, ListFineTuningEventsParams, ListFineTuningJobCheckpointsParams, ListFineTuningJobCheckpointsResponse, ListFineTuningJobEventsResponse, ListPaginatedFineTuningJobsParams, ListPaginatedFineTuningJobsResponse } from '.././schema';
export declare const getFineTuning: () => {
    createFineTuningJob: <TData = axios.AxiosResponse<FineTuningJob, any>>(createFineTuningJobRequest: CreateFineTuningJobRequest, options?: AxiosRequestConfig) => Promise<TData>;
    listPaginatedFineTuningJobs: <TData = axios.AxiosResponse<ListPaginatedFineTuningJobsResponse, any>>(params?: ListPaginatedFineTuningJobsParams, options?: AxiosRequestConfig) => Promise<TData>;
    retrieveFineTuningJob: <TData = axios.AxiosResponse<FineTuningJob, any>>(fineTuningJobId: string, options?: AxiosRequestConfig) => Promise<TData>;
    listFineTuningEvents: <TData = axios.AxiosResponse<ListFineTuningJobEventsResponse, any>>(fineTuningJobId: string, params?: ListFineTuningEventsParams, options?: AxiosRequestConfig) => Promise<TData>;
    cancelFineTuningJob: <TData = axios.AxiosResponse<FineTuningJob, any>>(fineTuningJobId: string, options?: AxiosRequestConfig) => Promise<TData>;
    listFineTuningJobCheckpoints: <TData = axios.AxiosResponse<ListFineTuningJobCheckpointsResponse, any>>(fineTuningJobId: string, params?: ListFineTuningJobCheckpointsParams, options?: AxiosRequestConfig) => Promise<TData>;
};
export type CreateFineTuningJobResult = AxiosResponse<FineTuningJob>;
export type ListPaginatedFineTuningJobsResult = AxiosResponse<ListPaginatedFineTuningJobsResponse>;
export type RetrieveFineTuningJobResult = AxiosResponse<FineTuningJob>;
export type ListFineTuningEventsResult = AxiosResponse<ListFineTuningJobEventsResponse>;
export type CancelFineTuningJobResult = AxiosResponse<FineTuningJob>;
export type ListFineTuningJobCheckpointsResult = AxiosResponse<ListFineTuningJobCheckpointsResponse>;
//# sourceMappingURL=fine-tuning.d.ts.map