/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateFineTuningCheckpointPermissionRequest,
  CreateFineTuningJobRequest,
  DeleteFineTuningCheckpointPermissionResponse,
  FineTuningJob,
  ListFineTuningCheckpointPermissionResponse,
  ListFineTuningCheckpointPermissionsParams,
  ListFineTuningEventsParams,
  ListFineTuningJobCheckpointsParams,
  ListFineTuningJobCheckpointsResponse,
  ListFineTuningJobEventsResponse,
  ListPaginatedFineTuningJobsParams,
  ListPaginatedFineTuningJobsResponse,
  RunGraderRequest,
  RunGraderResponse,
  ValidateGraderRequest,
  ValidateGraderResponse
} from '.././schema';




  export const getFineTuning = () => {
/**
 * Run a grader.

 * @summary Run grader
 */
const runGrader = <TData = AxiosResponse<RunGraderResponse>>(
    runGraderRequest: RunGraderRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/fine_tuning/alpha/graders/run`,
      runGraderRequest,options
    );
  }
/**
 * Validate a grader.

 * @summary Validate grader
 */
const validateGrader = <TData = AxiosResponse<ValidateGraderResponse>>(
    validateGraderRequest: ValidateGraderRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/fine_tuning/alpha/graders/validate`,
      validateGraderRequest,options
    );
  }
/**
 * **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).

Organization owners can use this endpoint to view all permissions for a fine-tuned model checkpoint.

 * @summary List checkpoint permissions
 */
const listFineTuningCheckpointPermissions = <TData = AxiosResponse<ListFineTuningCheckpointPermissionResponse>>(
    fineTunedModelCheckpoint: string,
    params?: ListFineTuningCheckpointPermissionsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/fine_tuning/checkpoints/${fineTunedModelCheckpoint}/permissions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * **NOTE:** Calling this endpoint requires an [admin API key](../admin-api-keys).

This enables organization owners to share fine-tuned models with other projects in their organization.

 * @summary Create checkpoint permissions
 */
const createFineTuningCheckpointPermission = <TData = AxiosResponse<ListFineTuningCheckpointPermissionResponse>>(
    fineTunedModelCheckpoint: string,
    createFineTuningCheckpointPermissionRequest: CreateFineTuningCheckpointPermissionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/fine_tuning/checkpoints/${fineTunedModelCheckpoint}/permissions`,
      createFineTuningCheckpointPermissionRequest,options
    );
  }
/**
 * **NOTE:** This endpoint requires an [admin API key](../admin-api-keys).

Organization owners can use this endpoint to delete a permission for a fine-tuned model checkpoint.

 * @summary Delete checkpoint permission
 */
const deleteFineTuningCheckpointPermission = <TData = AxiosResponse<DeleteFineTuningCheckpointPermissionResponse>>(
    fineTunedModelCheckpoint: string,
    permissionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/fine_tuning/checkpoints/${fineTunedModelCheckpoint}/permissions/${permissionId}`,options
    );
  }
/**
 * Creates a fine-tuning job which begins the process of creating a new model from a given dataset.

Response includes details of the enqueued job including job status and the name of the fine-tuned models once complete.

[Learn more about fine-tuning](https://platform.openai.com/docs/guides/model-optimization)

 * @summary Create fine-tuning job
 */
const createFineTuningJob = <TData = AxiosResponse<FineTuningJob>>(
    createFineTuningJobRequest: CreateFineTuningJobRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/fine_tuning/jobs`,
      createFineTuningJobRequest,options
    );
  }
/**
 * List your organization's fine-tuning jobs

 * @summary List fine-tuning jobs
 */
const listPaginatedFineTuningJobs = <TData = AxiosResponse<ListPaginatedFineTuningJobsResponse>>(
    params?: ListPaginatedFineTuningJobsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/fine_tuning/jobs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get info about a fine-tuning job.

[Learn more about fine-tuning](https://platform.openai.com/docs/guides/model-optimization)

 * @summary Retrieve fine-tuning job
 */
const retrieveFineTuningJob = <TData = AxiosResponse<FineTuningJob>>(
    fineTuningJobId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/fine_tuning/jobs/${fineTuningJobId}`,options
    );
  }
/**
 * Immediately cancel a fine-tune job.

 * @summary Cancel fine-tuning
 */
const cancelFineTuningJob = <TData = AxiosResponse<FineTuningJob>>(
    fineTuningJobId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/fine_tuning/jobs/${fineTuningJobId}/cancel`,undefined,options
    );
  }
/**
 * List checkpoints for a fine-tuning job.

 * @summary List fine-tuning checkpoints
 */
const listFineTuningJobCheckpoints = <TData = AxiosResponse<ListFineTuningJobCheckpointsResponse>>(
    fineTuningJobId: string,
    params?: ListFineTuningJobCheckpointsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/fine_tuning/jobs/${fineTuningJobId}/checkpoints`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get status updates for a fine-tuning job.

 * @summary List fine-tuning events
 */
const listFineTuningEvents = <TData = AxiosResponse<ListFineTuningJobEventsResponse>>(
    fineTuningJobId: string,
    params?: ListFineTuningEventsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/fine_tuning/jobs/${fineTuningJobId}/events`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Pause a fine-tune job.

 * @summary Pause fine-tuning
 */
const pauseFineTuningJob = <TData = AxiosResponse<FineTuningJob>>(
    fineTuningJobId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/fine_tuning/jobs/${fineTuningJobId}/pause`,undefined,options
    );
  }
/**
 * Resume a fine-tune job.

 * @summary Resume fine-tuning
 */
const resumeFineTuningJob = <TData = AxiosResponse<FineTuningJob>>(
    fineTuningJobId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/fine_tuning/jobs/${fineTuningJobId}/resume`,undefined,options
    );
  }
return {runGrader,validateGrader,listFineTuningCheckpointPermissions,createFineTuningCheckpointPermission,deleteFineTuningCheckpointPermission,createFineTuningJob,listPaginatedFineTuningJobs,retrieveFineTuningJob,cancelFineTuningJob,listFineTuningJobCheckpoints,listFineTuningEvents,pauseFineTuningJob,resumeFineTuningJob}};
export type RunGraderResult = AxiosResponse<RunGraderResponse>
export type ValidateGraderResult = AxiosResponse<ValidateGraderResponse>
export type ListFineTuningCheckpointPermissionsResult = AxiosResponse<ListFineTuningCheckpointPermissionResponse>
export type CreateFineTuningCheckpointPermissionResult = AxiosResponse<ListFineTuningCheckpointPermissionResponse>
export type DeleteFineTuningCheckpointPermissionResult = AxiosResponse<DeleteFineTuningCheckpointPermissionResponse>
export type CreateFineTuningJobResult = AxiosResponse<FineTuningJob>
export type ListPaginatedFineTuningJobsResult = AxiosResponse<ListPaginatedFineTuningJobsResponse>
export type RetrieveFineTuningJobResult = AxiosResponse<FineTuningJob>
export type CancelFineTuningJobResult = AxiosResponse<FineTuningJob>
export type ListFineTuningJobCheckpointsResult = AxiosResponse<ListFineTuningJobCheckpointsResponse>
export type ListFineTuningEventsResult = AxiosResponse<ListFineTuningJobEventsResponse>
export type PauseFineTuningJobResult = AxiosResponse<FineTuningJob>
export type ResumeFineTuningJobResult = AxiosResponse<FineTuningJob>
