/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { AdminApiKeysListOrder } from './adminApiKeysListOrder';

export type AdminApiKeysListParams = {
after?: string | null;
order?: AdminApiKeysListOrder;
limit?: number;
};
