/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

/**
 * The service tier used for processing the request. This field is only included if the `service_tier` parameter is specified in the request.
 * @nullable
 */
export type CreateChatCompletionStreamResponseServiceTier = typeof CreateChatCompletionStreamResponseServiceTier[keyof typeof CreateChatCompletionStreamResponseServiceTier] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateChatCompletionStreamResponseServiceTier = {
  scale: 'scale',
  default: 'default',
} as const;
