/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { CreateAssistantRequestToolResourcesFileSearchVectorStoresItemChunkingStrategy } from './createAssistantRequestToolResourcesFileSearchVectorStoresItemChunkingStrategy';
import type { CreateAssistantRequestToolResourcesFileSearchVectorStoresItemMetadata } from './createAssistantRequestToolResourcesFileSearchVectorStoresItemMetadata';

export type CreateAssistantRequestToolResourcesFileSearchVectorStoresItem = {
  /**
   * A list of [file](/docs/api-reference/files) IDs to add to the vector store. There can be a maximum of 10000 files in a vector store.

   * @maxItems 10000
   */
  file_ids?: string[];
  /** The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy. */
  chunking_strategy?: CreateAssistantRequestToolResourcesFileSearchVectorStoresItemChunkingStrategy;
  /** Set of 16 key-value pairs that can be attached to a vector store. This can be useful for storing additional information about the vector store in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
 */
  metadata?: CreateAssistantRequestToolResourcesFileSearchVectorStoresItemMetadata;
};
