/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { InputItem } from './inputItem';

export type CreateConversationItemsBody = {
  /**
   * The items to add to the conversation. You may add up to 20 items at a time.

   * @maxItems 20
   */
  items: InputItem[];
};
