/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { IncludeEnum } from './includeEnum';

export type GetResponseParams = {
/**
 * Additional fields to include in the response. See the `include`
parameter for Response creation above for more information.

 */
include?: IncludeEnum[];
/**
 * If set to true, the model response data will be streamed to the client
as it is generated using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format).
See the [Streaming section below](https://platform.openai.com/docs/api-reference/responses-streaming)
for more information.

 */
stream?: boolean;
/**
 * The sequence number of the event after which to start streaming.

 */
starting_after?: number;
/**
 * When true, stream obfuscation will be enabled. Stream obfuscation adds
random characters to an `obfuscation` field on streaming delta events
to normalize payload sizes as a mitigation to certain side-channel
attacks. These obfuscation fields are included by default, but add a
small amount of overhead to the data stream. You can set
`include_obfuscation` to false to optimize for bandwidth if you trust
the network links between your application and the OpenAI API.

 */
include_obfuscation?: boolean;
};
