/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { InputTextContent } from './inputTextContent';
import type { InputImageContent } from './inputImageContent';
import type { InputFileContent } from './inputFileContent';
import type { InputAudio } from './inputAudio';

export type InputContent = InputTextContent | InputImageContent | InputFileContent | InputAudio;
