/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type ListFilesResponseObject = typeof ListFilesResponseObject[keyof typeof ListFilesResponseObject];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListFilesResponseObject = {
  list: 'list',
} as const;
