/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */

export type ListPaginatedFineTuningJobsParams = {
/**
 * Identifier for the last job from the previous pagination request.
 */
after?: string;
/**
 * Number of fine-tuning jobs to retrieve.
 */
limit?: number;
/**
 * Optional metadata filter. To filter, use the syntax `metadata[k]=v`. Alternatively, set `metadata=null` to indicate no metadata.

 */
metadata?: {[key: string]: string} | null;
};
