/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { OrderEnum } from './orderEnum';

export type ListThreadsMethodParams = {
/**
 * Maximum number of thread items to return. Defaults to 20.
 */
limit?: number;
/**
 * Sort order for results by creation time. Defaults to `desc`.
 */
order?: OrderEnum;
/**
 * List items created after this thread item ID. Defaults to null for the first page.
 */
after?: string;
/**
 * List items created before this thread item ID. Defaults to null for the newest results.
 */
before?: string;
/**
 * Filter threads that belong to this user identifier. Defaults to null to return all users.
 */
user?: string;
};
