/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { LocalShellToolParamType } from './localShellToolParamType';

export interface LocalShellToolParam {
  /** The type of the local shell tool. Always `local_shell`. */
  type: LocalShellToolParamType;
}
