/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { OutputMessage } from './outputMessage';
import type { FileSearchToolCall } from './fileSearchToolCall';
import type { FunctionToolCall } from './functionToolCall';
import type { WebSearchToolCall } from './webSearchToolCall';
import type { ComputerToolCall } from './computerToolCall';
import type { ReasoningItem } from './reasoningItem';
import type { ImageGenToolCall } from './imageGenToolCall';
import type { CodeInterpreterToolCall } from './codeInterpreterToolCall';
import type { LocalShellToolCall } from './localShellToolCall';
import type { MCPToolCall } from './mCPToolCall';
import type { MCPListTools } from './mCPListTools';
import type { MCPApprovalRequest } from './mCPApprovalRequest';
import type { CustomToolCall } from './customToolCall';

export type OutputItem = OutputMessage | FileSearchToolCall | FunctionToolCall | WebSearchToolCall | ComputerToolCall | ReasoningItem | ImageGenToolCall | CodeInterpreterToolCall | LocalShellToolCall | MCPToolCall | MCPListTools | MCPApprovalRequest | CustomToolCall;
