/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RealtimeTruncationAnyOf } from './realtimeTruncationAnyOf';

/**
 * Controls how the realtime conversation is truncated prior to model inference.
The default is `auto`.

 */
export type RealtimeTruncation = 'auto' | 'disabled' | RealtimeTruncationAnyOf;
