/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RunStepStreamEventOneOfNineEvent } from './runStepStreamEventOneOfNineEvent';
import type { RunStepObject } from './runStepObject';

/**
 * Occurs when a [run step](/docs/api-reference/runs/step-object) fails.
 */
export type RunStepStreamEventOneOfNine = {
  event: RunStepStreamEventOneOfNineEvent;
  data: RunStepObject;
};
