/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { RunStepStreamEventOneOfEvent } from './runStepStreamEventOneOfEvent';
import type { RunStepObject } from './runStepObject';

/**
 * Occurs when a [run step](/docs/api-reference/runs/step-object) is created.
 */
export type RunStepStreamEventOneOf = {
  event: RunStepStreamEventOneOfEvent;
  data: RunStepObject;
};
