/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import type { FunctionTool } from './functionTool';
import type { FileSearchTool } from './fileSearchTool';
import type { ComputerUsePreviewTool } from './computerUsePreviewTool';
import type { WebSearchTool } from './webSearchTool';
import type { MCPTool } from './mCPTool';
import type { CodeInterpreterTool } from './codeInterpreterTool';
import type { ImageGenTool } from './imageGenTool';
import type { LocalShellToolParam } from './localShellToolParam';
import type { CustomToolParam } from './customToolParam';
import type { WebSearchPreviewTool } from './webSearchPreviewTool';

/**
 * A tool that can be used to generate a response.

 */
export type Tool = FunctionTool | FileSearchTool | ComputerUsePreviewTool | WebSearchTool | MCPTool | CodeInterpreterTool | ImageGenTool | LocalShellToolParam | CustomToolParam | WebSearchPreviewTool;
