/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * Lists the currently available models, and provides basic information about each one such as the owner and availability.
 * @summary List models
 */
export const listModelsResponse = zod.object({
  "object": zod.enum(['list']),
  "data": zod.array(zod.object({
  "id": zod.string().describe('The model identifier, which can be referenced in the API endpoints.'),
  "created": zod.number().describe('The Unix timestamp (in seconds) when the model was created.'),
  "object": zod.enum(['model']).describe('The object type, which is always \"model\".'),
  "owned_by": zod.string().describe('The organization that owns the model.')
}).describe('Describes an OpenAI model offering that can be used with the API.'))
})

/**
 * Retrieves a model instance, providing basic information about the model such as the owner and permissioning.
 * @summary Retrieve model
 */
export const retrieveModelParams = zod.object({
  "model": zod.string().describe('The ID of the model to use for this request')
})

export const retrieveModelResponse = zod.object({
  "id": zod.string().describe('The model identifier, which can be referenced in the API endpoints.'),
  "created": zod.number().describe('The Unix timestamp (in seconds) when the model was created.'),
  "object": zod.enum(['model']).describe('The object type, which is always \"model\".'),
  "owned_by": zod.string().describe('The organization that owns the model.')
}).describe('Describes an OpenAI model offering that can be used with the API.')

/**
 * Delete a fine-tuned model. You must have the Owner role in your organization to delete a model.
 * @summary Delete a fine-tuned model
 */
export const deleteModelParams = zod.object({
  "model": zod.string().describe('The model to delete')
})

export const deleteModelResponse = zod.object({
  "id": zod.string(),
  "deleted": zod.boolean(),
  "object": zod.string()
})

