/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * Creates an intermediate [Upload](https://platform.openai.com/docs/api-reference/uploads/object) object
that you can add [Parts](https://platform.openai.com/docs/api-reference/uploads/part-object) to.
Currently, an Upload can accept at most 8 GB in total and expires after an
hour after you create it.

Once you complete the Upload, we will create a
[File](https://platform.openai.com/docs/api-reference/files/object) object that contains all the parts
you uploaded. This File is usable in the rest of our platform as a regular
File object.

For certain `purpose` values, the correct `mime_type` must be specified.
Please refer to documentation for the
[supported MIME types for your use case](https://platform.openai.com/docs/assistants/tools/file-search#supported-files).

For guidance on the proper filename extensions for each purpose, please
follow the documentation on [creating a
File](https://platform.openai.com/docs/api-reference/files/create).

 * @summary Create upload
 */
export const createUploadBodyExpiresAfterSecondsMin = 3600;

export const createUploadBodyExpiresAfterSecondsMax = 2592000;


export const createUploadBody = zod.object({
  "filename": zod.string().describe('The name of the file to upload.\n'),
  "purpose": zod.enum(['assistants', 'batch', 'fine-tune', 'vision']).describe('The intended purpose of the uploaded file.\n\nSee the [documentation on File purposes](https://platform.openai.com/docs/api-reference/files/create#files-create-purpose).\n'),
  "bytes": zod.number().describe('The number of bytes in the file you are uploading.\n'),
  "mime_type": zod.string().describe('The MIME type of the file.\n\nThis must fall within the supported MIME types for your file purpose. See the supported MIME types for assistants and vision.\n'),
  "expires_after": zod.object({
  "anchor": zod.enum(['created_at']).describe('Anchor timestamp after which the expiration policy applies. Supported anchors: `created_at`.'),
  "seconds": zod.number().min(createUploadBodyExpiresAfterSecondsMin).max(createUploadBodyExpiresAfterSecondsMax).describe('The number of seconds after the anchor time that the file will expire. Must be between 3600 (1 hour) and 2592000 (30 days).')
}).optional().describe('The expiration policy for a file. By default, files with `purpose=batch` expire after 30 days and all other files are persisted until they are manually deleted.')
})

export const createUploadResponse = zod.object({
  "id": zod.string().describe('The Upload unique identifier, which can be referenced in API endpoints.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) for when the Upload was created.'),
  "filename": zod.string().describe('The name of the file to be uploaded.'),
  "bytes": zod.number().describe('The intended number of bytes to be uploaded.'),
  "purpose": zod.string().describe('The intended purpose of the file. [Please refer here](https://platform.openai.com/docs/api-reference/files/object#files/object-purpose) for acceptable values.'),
  "status": zod.enum(['pending', 'completed', 'cancelled', 'expired']).describe('The status of the Upload.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when the Upload will expire.'),
  "object": zod.enum(['upload']).describe('The object type, which is always \"upload\".'),
  "file": zod.object({
  "id": zod.string().describe('The file identifier, which can be referenced in the API endpoints.'),
  "bytes": zod.number().describe('The size of the file, in bytes.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) for when the file was created.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) for when the file will expire.'),
  "filename": zod.string().describe('The name of the file.'),
  "object": zod.enum(['file']).describe('The object type, which is always `file`.'),
  "purpose": zod.enum(['assistants', 'assistants_output', 'batch', 'batch_output', 'fine-tune', 'fine-tune-results', 'vision', 'user_data']).describe('The intended purpose of the file. Supported values are `assistants`, `assistants_output`, `batch`, `batch_output`, `fine-tune`, `fine-tune-results`, `vision`, and `user_data`.'),
  "status": zod.enum(['uploaded', 'processed', 'error']).describe('Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`.'),
  "status_details": zod.string().optional().describe('Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`.')
}).describe('The `File` object represents a document that has been uploaded to OpenAI.').and(zod.any().nullable().describe('The ready File object after the Upload is completed.')).optional()
}).describe('The Upload object can accept byte chunks in the form of Parts.\n')

/**
 * Cancels the Upload. No Parts may be added after an Upload is cancelled.

 * @summary Cancel upload
 */
export const cancelUploadParams = zod.object({
  "upload_id": zod.string().describe('The ID of the Upload.\n')
})

export const cancelUploadResponse = zod.object({
  "id": zod.string().describe('The Upload unique identifier, which can be referenced in API endpoints.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) for when the Upload was created.'),
  "filename": zod.string().describe('The name of the file to be uploaded.'),
  "bytes": zod.number().describe('The intended number of bytes to be uploaded.'),
  "purpose": zod.string().describe('The intended purpose of the file. [Please refer here](https://platform.openai.com/docs/api-reference/files/object#files/object-purpose) for acceptable values.'),
  "status": zod.enum(['pending', 'completed', 'cancelled', 'expired']).describe('The status of the Upload.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when the Upload will expire.'),
  "object": zod.enum(['upload']).describe('The object type, which is always \"upload\".'),
  "file": zod.object({
  "id": zod.string().describe('The file identifier, which can be referenced in the API endpoints.'),
  "bytes": zod.number().describe('The size of the file, in bytes.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) for when the file was created.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) for when the file will expire.'),
  "filename": zod.string().describe('The name of the file.'),
  "object": zod.enum(['file']).describe('The object type, which is always `file`.'),
  "purpose": zod.enum(['assistants', 'assistants_output', 'batch', 'batch_output', 'fine-tune', 'fine-tune-results', 'vision', 'user_data']).describe('The intended purpose of the file. Supported values are `assistants`, `assistants_output`, `batch`, `batch_output`, `fine-tune`, `fine-tune-results`, `vision`, and `user_data`.'),
  "status": zod.enum(['uploaded', 'processed', 'error']).describe('Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`.'),
  "status_details": zod.string().optional().describe('Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`.')
}).describe('The `File` object represents a document that has been uploaded to OpenAI.').and(zod.any().nullable().describe('The ready File object after the Upload is completed.')).optional()
}).describe('The Upload object can accept byte chunks in the form of Parts.\n')

/**
 * Completes the [Upload](https://platform.openai.com/docs/api-reference/uploads/object).

Within the returned Upload object, there is a nested [File](https://platform.openai.com/docs/api-reference/files/object) object that is ready to use in the rest of the platform.

You can specify the order of the Parts by passing in an ordered list of the Part IDs.

The number of bytes uploaded upon completion must match the number of bytes initially specified when creating the Upload object. No Parts may be added after an Upload is completed.

 * @summary Complete upload
 */
export const completeUploadParams = zod.object({
  "upload_id": zod.string().describe('The ID of the Upload.\n')
})

export const completeUploadBody = zod.object({
  "part_ids": zod.array(zod.string()).describe('The ordered list of Part IDs.\n'),
  "md5": zod.string().optional().describe('The optional md5 checksum for the file contents to verify if the bytes uploaded matches what you expect.\n')
})

export const completeUploadResponse = zod.object({
  "id": zod.string().describe('The Upload unique identifier, which can be referenced in API endpoints.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) for when the Upload was created.'),
  "filename": zod.string().describe('The name of the file to be uploaded.'),
  "bytes": zod.number().describe('The intended number of bytes to be uploaded.'),
  "purpose": zod.string().describe('The intended purpose of the file. [Please refer here](https://platform.openai.com/docs/api-reference/files/object#files/object-purpose) for acceptable values.'),
  "status": zod.enum(['pending', 'completed', 'cancelled', 'expired']).describe('The status of the Upload.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) for when the Upload will expire.'),
  "object": zod.enum(['upload']).describe('The object type, which is always \"upload\".'),
  "file": zod.object({
  "id": zod.string().describe('The file identifier, which can be referenced in the API endpoints.'),
  "bytes": zod.number().describe('The size of the file, in bytes.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) for when the file was created.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) for when the file will expire.'),
  "filename": zod.string().describe('The name of the file.'),
  "object": zod.enum(['file']).describe('The object type, which is always `file`.'),
  "purpose": zod.enum(['assistants', 'assistants_output', 'batch', 'batch_output', 'fine-tune', 'fine-tune-results', 'vision', 'user_data']).describe('The intended purpose of the file. Supported values are `assistants`, `assistants_output`, `batch`, `batch_output`, `fine-tune`, `fine-tune-results`, `vision`, and `user_data`.'),
  "status": zod.enum(['uploaded', 'processed', 'error']).describe('Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`.'),
  "status_details": zod.string().optional().describe('Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`.')
}).describe('The `File` object represents a document that has been uploaded to OpenAI.').and(zod.any().nullable().describe('The ready File object after the Upload is completed.')).optional()
}).describe('The Upload object can accept byte chunks in the form of Parts.\n')

/**
 * Adds a [Part](https://platform.openai.com/docs/api-reference/uploads/part-object) to an [Upload](https://platform.openai.com/docs/api-reference/uploads/object) object. A Part represents a chunk of bytes from the file you are trying to upload.

Each Part can be at most 64 MB, and you can add Parts until you hit the Upload maximum of 8 GB.

It is possible to add multiple Parts in parallel. You can decide the intended order of the Parts when you [complete the Upload](https://platform.openai.com/docs/api-reference/uploads/complete).

 * @summary Add upload part
 */
export const addUploadPartParams = zod.object({
  "upload_id": zod.string().describe('The ID of the Upload.\n')
})

export const addUploadPartBody = zod.object({
  "data": zod.instanceof(File).describe('The chunk of bytes for this Part.\n')
})

export const addUploadPartResponse = zod.object({
  "id": zod.string().describe('The upload Part unique identifier, which can be referenced in API endpoints.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) for when the Part was created.'),
  "upload_id": zod.string().describe('The ID of the Upload object that this Part was added to.'),
  "object": zod.enum(['upload.part']).describe('The object type, which is always `upload.part`.')
}).describe('The upload Part represents a chunk of bytes we can add to an Upload object.\n')

