/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateVideoBody,
  CreateVideoRemixBody,
  DeletedVideoResource,
  ListVideosParams,
  RetrieveVideoContentParams,
  VideoListResource,
  VideoResource
} from '.././schema';




  export const getVideos = () => {
/**
 * Create a video
 * @summary Create video
 */
const createVideo = <TData = AxiosResponse<VideoResource>>(
    createVideoBody: CreateVideoBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
if(createVideoBody.model !== undefined) {
 formData.append('model', createVideoBody.model)
 }
formData.append('prompt', createVideoBody.prompt)
if(createVideoBody.input_reference !== undefined) {
 formData.append('input_reference', createVideoBody.input_reference)
 }
if(createVideoBody.seconds !== undefined) {
 formData.append('seconds', createVideoBody.seconds)
 }
if(createVideoBody.size !== undefined) {
 formData.append('size', createVideoBody.size)
 }

    return axios.default.post(
      `/videos`,
      formData,options
    );
  }
/**
 * List videos
 * @summary List videos
 */
const listVideos = <TData = AxiosResponse<VideoListResource>>(
    params?: ListVideosParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/videos`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieve a video
 * @summary Retrieve video
 */
const getVideo = <TData = AxiosResponse<VideoResource>>(
    videoId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/videos/${videoId}`,options
    );
  }
/**
 * Delete a video
 * @summary Delete video
 */
const deleteVideo = <TData = AxiosResponse<DeletedVideoResource>>(
    videoId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/videos/${videoId}`,options
    );
  }
/**
 * Download video content
 * @summary Retrieve video content
 */
const retrieveVideoContent = <TData = AxiosResponse<Blob | string>>(
    videoId: string,
    params?: RetrieveVideoContentParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/videos/${videoId}/content`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a video remix
 * @summary Remix video
 */
const createVideoRemix = <TData = AxiosResponse<VideoResource>>(
    videoId: string,
    createVideoRemixBody: CreateVideoRemixBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append('prompt', createVideoRemixBody.prompt)

    return axios.default.post(
      `/videos/${videoId}/remix`,
      formData,options
    );
  }
return {createVideo,listVideos,getVideo,deleteVideo,retrieveVideoContent,createVideoRemix}};
export type CreateVideoResult = AxiosResponse<VideoResource>
export type ListVideosResult = AxiosResponse<VideoListResource>
export type GetVideoResult = AxiosResponse<VideoResource>
export type DeleteVideoResult = AxiosResponse<DeletedVideoResource>
export type RetrieveVideoContentResult = AxiosResponse<Blob | string>
export type CreateVideoRemixResult = AxiosResponse<VideoResource>
