/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateCompletionRequest,
  CreateCompletionResponse
} from '.././schema';




  export const getCompletions = () => {
/**
 * Creates a completion for the provided prompt and parameters.
 * @summary Create completion
 */
const createCompletion = <TData = AxiosResponse<CreateCompletionResponse>>(
    createCompletionRequest: CreateCompletionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/completions`,
      createCompletionRequest,options
    );
  }
return {createCompletion}};
export type CreateCompletionResult = AxiosResponse<CreateCompletionResponse>
