/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * Returns a list of invites in the organization.
 * @summary List invites
 */
export const listInvitesQueryLimitDefault = 20;

export const listInvitesQueryParams = zod.object({
  "limit": zod.number().optional().describe('A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.\n'),
  "after": zod.string().optional().describe('A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.\n')
})

export const listInvitesResponse = zod.object({
  "object": zod.enum(['list']).describe('The object type, which is always `list`'),
  "data": zod.array(zod.object({
  "object": zod.enum(['organization.invite']).describe('The object type, which is always `organization.invite`'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "email": zod.string().describe('The email address of the individual to whom the invite was sent'),
  "role": zod.enum(['owner', 'reader']).describe('`owner` or `reader`'),
  "status": zod.enum(['accepted', 'expired', 'pending']).describe('`accepted`,`expired`, or `pending`'),
  "invited_at": zod.number().describe('The Unix timestamp (in seconds) of when the invite was sent.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) of when the invite expires.'),
  "accepted_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the invite was accepted.'),
  "projects": zod.array(zod.object({
  "id": zod.string().optional().describe('Project\'s public ID'),
  "role": zod.enum(['member', 'owner']).optional().describe('Project membership role')
})).optional().describe('The projects that were granted membership upon acceptance of the invite.')
}).describe('Represents an individual `invite` to the organization.')),
  "first_id": zod.string().optional().describe('The first `invite_id` in the retrieved `list`'),
  "last_id": zod.string().optional().describe('The last `invite_id` in the retrieved `list`'),
  "has_more": zod.boolean().optional().describe('The `has_more` property is used for pagination to indicate there are additional results.')
})

/**
 * Create an invite for a user to the organization. The invite must be accepted by the user before they have access to the organization.
 * @summary Create invite
 */
export const inviteUserBody = zod.object({
  "email": zod.string().describe('Send an email to this address'),
  "role": zod.enum(['reader', 'owner']).describe('`owner` or `reader`'),
  "projects": zod.array(zod.object({
  "id": zod.string().describe('Project\'s public ID'),
  "role": zod.enum(['member', 'owner']).describe('Project membership role')
})).optional().describe('An array of projects to which membership is granted at the same time the org invite is accepted. If omitted, the user will be invited to the default project for compatibility with legacy behavior.')
})

export const inviteUserResponse = zod.object({
  "object": zod.enum(['organization.invite']).describe('The object type, which is always `organization.invite`'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "email": zod.string().describe('The email address of the individual to whom the invite was sent'),
  "role": zod.enum(['owner', 'reader']).describe('`owner` or `reader`'),
  "status": zod.enum(['accepted', 'expired', 'pending']).describe('`accepted`,`expired`, or `pending`'),
  "invited_at": zod.number().describe('The Unix timestamp (in seconds) of when the invite was sent.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) of when the invite expires.'),
  "accepted_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the invite was accepted.'),
  "projects": zod.array(zod.object({
  "id": zod.string().optional().describe('Project\'s public ID'),
  "role": zod.enum(['member', 'owner']).optional().describe('Project membership role')
})).optional().describe('The projects that were granted membership upon acceptance of the invite.')
}).describe('Represents an individual `invite` to the organization.')

/**
 * Retrieves an invite.
 * @summary Retrieve invite
 */
export const retrieveInviteParams = zod.object({
  "invite_id": zod.string().describe('The ID of the invite to retrieve.')
})

export const retrieveInviteResponse = zod.object({
  "object": zod.enum(['organization.invite']).describe('The object type, which is always `organization.invite`'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "email": zod.string().describe('The email address of the individual to whom the invite was sent'),
  "role": zod.enum(['owner', 'reader']).describe('`owner` or `reader`'),
  "status": zod.enum(['accepted', 'expired', 'pending']).describe('`accepted`,`expired`, or `pending`'),
  "invited_at": zod.number().describe('The Unix timestamp (in seconds) of when the invite was sent.'),
  "expires_at": zod.number().describe('The Unix timestamp (in seconds) of when the invite expires.'),
  "accepted_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the invite was accepted.'),
  "projects": zod.array(zod.object({
  "id": zod.string().optional().describe('Project\'s public ID'),
  "role": zod.enum(['member', 'owner']).optional().describe('Project membership role')
})).optional().describe('The projects that were granted membership upon acceptance of the invite.')
}).describe('Represents an individual `invite` to the organization.')

/**
 * Delete an invite. If the invite has already been accepted, it cannot be deleted.
 * @summary Delete invite
 */
export const deleteInviteParams = zod.object({
  "invite_id": zod.string().describe('The ID of the invite to delete.')
})

export const deleteInviteResponse = zod.object({
  "object": zod.enum(['organization.invite.deleted']).describe('The object type, which is always `organization.invite.deleted`'),
  "id": zod.string(),
  "deleted": zod.boolean()
})

