/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateResponse,
  GetResponseParams,
  ListInputItemsParams,
  Response,
  ResponseItemList,
  ResponseStreamEvent
} from '.././schema';




  export const getResponses = () => {
/**
 * Creates a model response. Provide [text](https://platform.openai.com/docs/guides/text) or
[image](https://platform.openai.com/docs/guides/images) inputs to generate [text](https://platform.openai.com/docs/guides/text)
or [JSON](https://platform.openai.com/docs/guides/structured-outputs) outputs. Have the model call
your own [custom code](https://platform.openai.com/docs/guides/function-calling) or use built-in
[tools](https://platform.openai.com/docs/guides/tools) like [web search](https://platform.openai.com/docs/guides/tools-web-search)
or [file search](https://platform.openai.com/docs/guides/tools-file-search) to use your own data
as input for the model's response.

 * @summary Create a model response
 */
const createResponse = <TData = AxiosResponse<Response | ResponseStreamEvent>>(
    createResponse: CreateResponse, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/responses`,
      createResponse,options
    );
  }
/**
 * Retrieves a model response with the given ID.

 * @summary Get a model response
 */
const getResponse = <TData = AxiosResponse<Response>>(
    responseId: string,
    params?: GetResponseParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/responses/${responseId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Deletes a model response with the given ID.

 * @summary Delete a model response
 */
const deleteResponse = <TData = AxiosResponse<void>>(
    responseId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/responses/${responseId}`,options
    );
  }
/**
 * Cancels a model response with the given ID. Only responses created with
the `background` parameter set to `true` can be cancelled.
[Learn more](https://platform.openai.com/docs/guides/background).

 * @summary Cancel a response
 */
const cancelResponse = <TData = AxiosResponse<Response>>(
    responseId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/responses/${responseId}/cancel`,undefined,options
    );
  }
/**
 * Returns a list of input items for a given response.
 * @summary List input items
 */
const listInputItems = <TData = AxiosResponse<ResponseItemList>>(
    responseId: string,
    params?: ListInputItemsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/responses/${responseId}/input_items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {createResponse,getResponse,deleteResponse,cancelResponse,listInputItems}};
export type CreateResponseResult = AxiosResponse<Response | ResponseStreamEvent>
export type GetResponseResult = AxiosResponse<Response>
export type DeleteResponseResult = AxiosResponse<void>
export type CancelResponseResult = AxiosResponse<Response>
export type ListInputItemsResult = AxiosResponse<ResponseItemList>
