/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateModerationRequest,
  CreateModerationResponse
} from '.././schema';




  export const getModerations = () => {
/**
 * Classifies if text and/or image inputs are potentially harmful. Learn
more in the [moderation guide](https://platform.openai.com/docs/guides/moderation).

 * @summary Create moderation
 */
const createModeration = <TData = AxiosResponse<CreateModerationResponse>>(
    createModerationRequest: CreateModerationRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/moderations`,
      createModerationRequest,options
    );
  }
return {createModeration}};
export type CreateModerationResult = AxiosResponse<CreateModerationResponse>
