/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { CreateModerationRequest, CreateModerationResponse } from '.././schema';
export declare const getModerations: () => {
    createModeration: <TData = axios.AxiosResponse<CreateModerationResponse, any>>(createModerationRequest: CreateModerationRequest, options?: AxiosRequestConfig) => Promise<TData>;
};
export type CreateModerationResult = AxiosResponse<CreateModerationResponse>;
//# sourceMappingURL=moderations.d.ts.map