/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { Batch, CreateBatchBody, ListBatchesParams, ListBatchesResponse } from '.././schema';
export declare const getBatch: () => {
    createBatch: <TData = axios.AxiosResponse<Batch, any>>(createBatchBody: CreateBatchBody, options?: AxiosRequestConfig) => Promise<TData>;
    listBatches: <TData = axios.AxiosResponse<ListBatchesResponse, any>>(params?: ListBatchesParams, options?: AxiosRequestConfig) => Promise<TData>;
    retrieveBatch: <TData = axios.AxiosResponse<Batch, any>>(batchId: string, options?: AxiosRequestConfig) => Promise<TData>;
    cancelBatch: <TData = axios.AxiosResponse<Batch, any>>(batchId: string, options?: AxiosRequestConfig) => Promise<TData>;
};
export type CreateBatchResult = AxiosResponse<Batch>;
export type ListBatchesResult = AxiosResponse<ListBatchesResponse>;
export type RetrieveBatchResult = AxiosResponse<Batch>;
export type CancelBatchResult = AxiosResponse<Batch>;
//# sourceMappingURL=batch.d.ts.map