/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ConversationItem,
  ConversationItemList,
  ConversationResource,
  CreateConversationBody,
  CreateConversationItemsBody,
  CreateConversationItemsParams,
  DeletedConversationResource,
  GetConversationItemParams,
  ListConversationItemsParams,
  UpdateConversationBody
} from '.././schema';




  export const getConversations = () => {
/**
 * Create items in a conversation with the given ID.
 * @summary Create items
 */
const createConversationItems = <TData = AxiosResponse<ConversationItemList>>(
    conversationId: string,
    createConversationItemsBody: CreateConversationItemsBody,
    params?: CreateConversationItemsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/conversations/${conversationId}/items`,
      createConversationItemsBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * List all items for a conversation with the given ID.
 * @summary List items
 */
const listConversationItems = <TData = AxiosResponse<ConversationItemList>>(
    conversationId: string,
    params?: ListConversationItemsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/conversations/${conversationId}/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get a single item from a conversation with the given IDs.
 * @summary Retrieve an item
 */
const getConversationItem = <TData = AxiosResponse<ConversationItem>>(
    conversationId: string,
    itemId: string,
    params?: GetConversationItemParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/conversations/${conversationId}/items/${itemId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Delete an item from a conversation with the given IDs.
 * @summary Delete an item
 */
const deleteConversationItem = <TData = AxiosResponse<ConversationResource>>(
    conversationId: string,
    itemId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/conversations/${conversationId}/items/${itemId}`,options
    );
  }
/**
 * Create a conversation.
 * @summary Create a conversation
 */
const createConversation = <TData = AxiosResponse<ConversationResource>>(
    createConversationBody: CreateConversationBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/conversations`,
      createConversationBody,options
    );
  }
/**
 * Get a conversation
 * @summary Retrieve a conversation
 */
const getConversation = <TData = AxiosResponse<ConversationResource>>(
    conversationId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/conversations/${conversationId}`,options
    );
  }
/**
 * Delete a conversation. Items in the conversation will not be deleted.
 * @summary Delete a conversation
 */
const deleteConversation = <TData = AxiosResponse<DeletedConversationResource>>(
    conversationId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/conversations/${conversationId}`,options
    );
  }
/**
 * Update a conversation
 * @summary Update a conversation
 */
const updateConversation = <TData = AxiosResponse<ConversationResource>>(
    conversationId: string,
    updateConversationBody: UpdateConversationBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/conversations/${conversationId}`,
      updateConversationBody,options
    );
  }
return {createConversationItems,listConversationItems,getConversationItem,deleteConversationItem,createConversation,getConversation,deleteConversation,updateConversation}};
export type CreateConversationItemsResult = AxiosResponse<ConversationItemList>
export type ListConversationItemsResult = AxiosResponse<ConversationItemList>
export type GetConversationItemResult = AxiosResponse<ConversationItem>
export type DeleteConversationItemResult = AxiosResponse<ConversationResource>
export type CreateConversationResult = AxiosResponse<ConversationResource>
export type GetConversationResult = AxiosResponse<ConversationResource>
export type DeleteConversationResult = AxiosResponse<DeletedConversationResource>
export type UpdateConversationResult = AxiosResponse<ConversationResource>
