/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { Invite, InviteDeleteResponse, InviteListResponse, InviteRequest, ListInvitesParams } from '.././schema';
export declare const getInvites: () => {
    listInvites: <TData = axios.AxiosResponse<InviteListResponse, any>>(params?: ListInvitesParams, options?: AxiosRequestConfig) => Promise<TData>;
    inviteUser: <TData = axios.AxiosResponse<Invite, any>>(inviteRequest: InviteRequest, options?: AxiosRequestConfig) => Promise<TData>;
    retrieveInvite: <TData = axios.AxiosResponse<Invite, any>>(inviteId: string, options?: AxiosRequestConfig) => Promise<TData>;
    deleteInvite: <TData = axios.AxiosResponse<InviteDeleteResponse, any>>(inviteId: string, options?: AxiosRequestConfig) => Promise<TData>;
};
export type ListInvitesResult = AxiosResponse<InviteListResponse>;
export type InviteUserResult = AxiosResponse<Invite>;
export type RetrieveInviteResult = AxiosResponse<Invite>;
export type DeleteInviteResult = AxiosResponse<InviteDeleteResponse>;
//# sourceMappingURL=invites.d.ts.map