/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  UsageAudioSpeechesParams,
  UsageAudioTranscriptionsParams,
  UsageCodeInterpreterSessionsParams,
  UsageCompletionsParams,
  UsageCostsParams,
  UsageEmbeddingsParams,
  UsageImagesParams,
  UsageModerationsParams,
  UsageResponse,
  UsageVectorStoresParams
} from '.././schema';




  export const getUsage = () => {
/**
 * Get costs details for the organization.
 * @summary Costs
 */
const usageCosts = <TData = AxiosResponse<UsageResponse>>(
    params: UsageCostsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/costs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get audio speeches usage details for the organization.
 * @summary Audio speeches
 */
const usageAudioSpeeches = <TData = AxiosResponse<UsageResponse>>(
    params: UsageAudioSpeechesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/audio_speeches`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get audio transcriptions usage details for the organization.
 * @summary Audio transcriptions
 */
const usageAudioTranscriptions = <TData = AxiosResponse<UsageResponse>>(
    params: UsageAudioTranscriptionsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/audio_transcriptions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get code interpreter sessions usage details for the organization.
 * @summary Code interpreter sessions
 */
const usageCodeInterpreterSessions = <TData = AxiosResponse<UsageResponse>>(
    params: UsageCodeInterpreterSessionsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/code_interpreter_sessions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get completions usage details for the organization.
 * @summary Completions
 */
const usageCompletions = <TData = AxiosResponse<UsageResponse>>(
    params: UsageCompletionsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/completions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get embeddings usage details for the organization.
 * @summary Embeddings
 */
const usageEmbeddings = <TData = AxiosResponse<UsageResponse>>(
    params: UsageEmbeddingsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/embeddings`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get images usage details for the organization.
 * @summary Images
 */
const usageImages = <TData = AxiosResponse<UsageResponse>>(
    params: UsageImagesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/images`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get moderations usage details for the organization.
 * @summary Moderations
 */
const usageModerations = <TData = AxiosResponse<UsageResponse>>(
    params: UsageModerationsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/moderations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get vector stores usage details for the organization.
 * @summary Vector stores
 */
const usageVectorStores = <TData = AxiosResponse<UsageResponse>>(
    params: UsageVectorStoresParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/usage/vector_stores`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {usageCosts,usageAudioSpeeches,usageAudioTranscriptions,usageCodeInterpreterSessions,usageCompletions,usageEmbeddings,usageImages,usageModerations,usageVectorStores}};
export type UsageCostsResult = AxiosResponse<UsageResponse>
export type UsageAudioSpeechesResult = AxiosResponse<UsageResponse>
export type UsageAudioTranscriptionsResult = AxiosResponse<UsageResponse>
export type UsageCodeInterpreterSessionsResult = AxiosResponse<UsageResponse>
export type UsageCompletionsResult = AxiosResponse<UsageResponse>
export type UsageEmbeddingsResult = AxiosResponse<UsageResponse>
export type UsageImagesResult = AxiosResponse<UsageResponse>
export type UsageModerationsResult = AxiosResponse<UsageResponse>
export type UsageVectorStoresResult = AxiosResponse<UsageResponse>
