/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * Get costs details for the organization.
 * @summary Costs
 */
export const usageCostsQueryBucketWidthDefault = "1d";export const usageCostsQueryLimitDefault = 7;

export const usageCostsQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1d']).optional().describe('Width of each time bucket in response. Currently only `1d` is supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only costs for these projects.'),
  "group_by": zod.array(zod.enum(['project_id', 'line_item'])).optional().describe('Group the costs by the specified fields. Support fields include `project_id`, `line_item` and any combination of them.'),
  "limit": zod.number().optional().describe('A limit on the number of buckets to be returned. Limit can range between 1 and 180, and the default is 7.\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageCostsResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get audio speeches usage details for the organization.
 * @summary Audio speeches
 */
export const usageAudioSpeechesQueryBucketWidthDefault = "1d";

export const usageAudioSpeechesQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "user_ids": zod.array(zod.string()).optional().describe('Return only usage for these users.'),
  "api_key_ids": zod.array(zod.string()).optional().describe('Return only usage for these API keys.'),
  "models": zod.array(zod.string()).optional().describe('Return only usage for these models.'),
  "group_by": zod.array(zod.enum(['project_id', 'user_id', 'api_key_id', 'model'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`, `user_id`, `api_key_id`, `model` or any combination of them.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageAudioSpeechesResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get audio transcriptions usage details for the organization.
 * @summary Audio transcriptions
 */
export const usageAudioTranscriptionsQueryBucketWidthDefault = "1d";

export const usageAudioTranscriptionsQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "user_ids": zod.array(zod.string()).optional().describe('Return only usage for these users.'),
  "api_key_ids": zod.array(zod.string()).optional().describe('Return only usage for these API keys.'),
  "models": zod.array(zod.string()).optional().describe('Return only usage for these models.'),
  "group_by": zod.array(zod.enum(['project_id', 'user_id', 'api_key_id', 'model'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`, `user_id`, `api_key_id`, `model` or any combination of them.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageAudioTranscriptionsResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get code interpreter sessions usage details for the organization.
 * @summary Code interpreter sessions
 */
export const usageCodeInterpreterSessionsQueryBucketWidthDefault = "1d";

export const usageCodeInterpreterSessionsQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "group_by": zod.array(zod.enum(['project_id'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageCodeInterpreterSessionsResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get completions usage details for the organization.
 * @summary Completions
 */
export const usageCompletionsQueryBucketWidthDefault = "1d";

export const usageCompletionsQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "user_ids": zod.array(zod.string()).optional().describe('Return only usage for these users.'),
  "api_key_ids": zod.array(zod.string()).optional().describe('Return only usage for these API keys.'),
  "models": zod.array(zod.string()).optional().describe('Return only usage for these models.'),
  "batch": zod.boolean().optional().describe('If `true`, return batch jobs only. If `false`, return non-batch jobs only. By default, return both.\n'),
  "group_by": zod.array(zod.enum(['project_id', 'user_id', 'api_key_id', 'model', 'batch', 'service_tier'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`, `user_id`, `api_key_id`, `model`, `batch`, `service_tier` or any combination of them.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageCompletionsResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get embeddings usage details for the organization.
 * @summary Embeddings
 */
export const usageEmbeddingsQueryBucketWidthDefault = "1d";

export const usageEmbeddingsQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "user_ids": zod.array(zod.string()).optional().describe('Return only usage for these users.'),
  "api_key_ids": zod.array(zod.string()).optional().describe('Return only usage for these API keys.'),
  "models": zod.array(zod.string()).optional().describe('Return only usage for these models.'),
  "group_by": zod.array(zod.enum(['project_id', 'user_id', 'api_key_id', 'model'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`, `user_id`, `api_key_id`, `model` or any combination of them.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageEmbeddingsResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get images usage details for the organization.
 * @summary Images
 */
export const usageImagesQueryBucketWidthDefault = "1d";

export const usageImagesQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "sources": zod.array(zod.enum(['image.generation', 'image.edit', 'image.variation'])).optional().describe('Return only usages for these sources. Possible values are `image.generation`, `image.edit`, `image.variation` or any combination of them.'),
  "sizes": zod.array(zod.enum(['256x256', '512x512', '1024x1024', '1792x1792', '1024x1792'])).optional().describe('Return only usages for these image sizes. Possible values are `256x256`, `512x512`, `1024x1024`, `1792x1792`, `1024x1792` or any combination of them.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "user_ids": zod.array(zod.string()).optional().describe('Return only usage for these users.'),
  "api_key_ids": zod.array(zod.string()).optional().describe('Return only usage for these API keys.'),
  "models": zod.array(zod.string()).optional().describe('Return only usage for these models.'),
  "group_by": zod.array(zod.enum(['project_id', 'user_id', 'api_key_id', 'model', 'size', 'source'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`, `user_id`, `api_key_id`, `model`, `size`, `source` or any combination of them.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageImagesResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get moderations usage details for the organization.
 * @summary Moderations
 */
export const usageModerationsQueryBucketWidthDefault = "1d";

export const usageModerationsQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "user_ids": zod.array(zod.string()).optional().describe('Return only usage for these users.'),
  "api_key_ids": zod.array(zod.string()).optional().describe('Return only usage for these API keys.'),
  "models": zod.array(zod.string()).optional().describe('Return only usage for these models.'),
  "group_by": zod.array(zod.enum(['project_id', 'user_id', 'api_key_id', 'model'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`, `user_id`, `api_key_id`, `model` or any combination of them.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageModerationsResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

/**
 * Get vector stores usage details for the organization.
 * @summary Vector stores
 */
export const usageVectorStoresQueryBucketWidthDefault = "1d";

export const usageVectorStoresQueryParams = zod.object({
  "start_time": zod.number().describe('Start time (Unix seconds) of the query time range, inclusive.'),
  "end_time": zod.number().optional().describe('End time (Unix seconds) of the query time range, exclusive.'),
  "bucket_width": zod.enum(['1m', '1h', '1d']).optional().describe('Width of each time bucket in response. Currently `1m`, `1h` and `1d` are supported, default to `1d`.'),
  "project_ids": zod.array(zod.string()).optional().describe('Return only usage for these projects.'),
  "group_by": zod.array(zod.enum(['project_id'])).optional().describe('Group the usage data by the specified fields. Support fields include `project_id`.'),
  "limit": zod.number().optional().describe('Specifies the number of buckets to return.\n- `bucket_width=1d`: default: 7, max: 31\n- `bucket_width=1h`: default: 24, max: 168\n- `bucket_width=1m`: default: 60, max: 1440\n'),
  "page": zod.string().optional().describe('A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.')
})

export const usageVectorStoresResponse = zod.object({
  "object": zod.enum(['page']),
  "data": zod.array(zod.object({
  "object": zod.enum(['bucket']),
  "start_time": zod.number(),
  "end_time": zod.number(),
  "result": zod.array(zod.discriminatedUnion('object', [zod.object({
  "object": zod.enum(['organization.usage.completions.result']),
  "input_tokens": zod.number().describe('The aggregated number of text input tokens used, including cached tokens. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_cached_tokens": zod.number().optional().describe('The aggregated number of text input tokens that has been cached from previous requests. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "output_tokens": zod.number().describe('The aggregated number of text output tokens used. For customers subscribe to scale tier, this includes scale tier tokens.'),
  "input_audio_tokens": zod.number().optional().describe('The aggregated number of audio input tokens used, including cached tokens.'),
  "output_audio_tokens": zod.number().optional().describe('The aggregated number of audio output tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional(),
  "batch": zod.boolean().describe('When `group_by=batch`, this field tells whether the grouped usage result is batch or not.').or(zod.null()).optional(),
  "service_tier": zod.string().describe('When `group_by=service_tier`, this field provides the service tier of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated completions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.embeddings.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated embeddings usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.moderations.result']),
  "input_tokens": zod.number().describe('The aggregated number of input tokens used.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated moderations usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.images.result']),
  "images": zod.number().describe('The number of images processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "source": zod.string().describe('When `group_by=source`, this field provides the source of the grouped usage result, possible values are `image.generation`, `image.edit`, `image.variation`.').or(zod.null()).optional(),
  "size": zod.string().describe('When `group_by=size`, this field provides the image size of the grouped usage result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated images usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_speeches.result']),
  "characters": zod.number().describe('The number of characters processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio speeches usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.audio_transcriptions.result']),
  "seconds": zod.number().describe('The number of seconds processed.'),
  "num_model_requests": zod.number().describe('The count of requests made to the model.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional(),
  "user_id": zod.string().describe('When `group_by=user_id`, this field provides the user ID of the grouped usage result.').or(zod.null()).optional(),
  "api_key_id": zod.string().describe('When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.').or(zod.null()).optional(),
  "model": zod.string().describe('When `group_by=model`, this field provides the model name of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated audio transcriptions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.vector_stores.result']),
  "usage_bytes": zod.number().describe('The vector stores usage in bytes.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated vector stores usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.usage.code_interpreter_sessions.result']),
  "num_sessions": zod.number().optional().describe('The number of code interpreter sessions.'),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped usage result.').or(zod.null()).optional()
}).describe('The aggregated code interpreter sessions usage details of the specific time bucket.'),zod.object({
  "object": zod.enum(['organization.costs.result']),
  "amount": zod.object({
  "value": zod.number().optional().describe('The numeric value of the cost.'),
  "currency": zod.string().optional().describe('Lowercase ISO-4217 currency e.g. \"usd\"')
}).optional().describe('The monetary value in its associated currency.'),
  "line_item": zod.string().describe('When `group_by=line_item`, this field provides the line item of the grouped costs result.').or(zod.null()).optional(),
  "project_id": zod.string().describe('When `group_by=project_id`, this field provides the project ID of the grouped costs result.').or(zod.null()).optional()
}).describe('The aggregated costs details of the specific time bucket.')]))
})),
  "has_more": zod.boolean(),
  "next_page": zod.string()
})

