/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { AssistantObject, CreateAssistantRequest, CreateMessageRequest, CreateRunRequest, CreateThreadAndRunRequest, CreateThreadRequest, DeleteAssistantResponse, DeleteMessageResponse, DeleteThreadResponse, ListAssistantsParams, ListAssistantsResponse, ListMessagesParams, ListMessagesResponse, ListRunStepsParams, ListRunStepsResponse, ListRunsParams, ListRunsResponse, MessageObject, ModifyAssistantRequest, ModifyMessageRequest, ModifyRunRequest, ModifyThreadRequest, RunObject, RunStepObject, SubmitToolOutputsRunRequest, ThreadObject } from '.././schema';
export declare const getAssistants: () => {
    listAssistants: <TData = axios.AxiosResponse<ListAssistantsResponse, any>>(params?: ListAssistantsParams, options?: AxiosRequestConfig) => Promise<TData>;
    createAssistant: <TData = axios.AxiosResponse<AssistantObject, any>>(createAssistantRequest: CreateAssistantRequest, options?: AxiosRequestConfig) => Promise<TData>;
    getAssistant: <TData = axios.AxiosResponse<AssistantObject, any>>(assistantId: string, options?: AxiosRequestConfig) => Promise<TData>;
    modifyAssistant: <TData = axios.AxiosResponse<AssistantObject, any>>(assistantId: string, modifyAssistantRequest: ModifyAssistantRequest, options?: AxiosRequestConfig) => Promise<TData>;
    deleteAssistant: <TData = axios.AxiosResponse<DeleteAssistantResponse, any>>(assistantId: string, options?: AxiosRequestConfig) => Promise<TData>;
    createThread: <TData = axios.AxiosResponse<ThreadObject, any>>(createThreadRequest: CreateThreadRequest, options?: AxiosRequestConfig) => Promise<TData>;
    getThread: <TData = axios.AxiosResponse<ThreadObject, any>>(threadId: string, options?: AxiosRequestConfig) => Promise<TData>;
    modifyThread: <TData = axios.AxiosResponse<ThreadObject, any>>(threadId: string, modifyThreadRequest: ModifyThreadRequest, options?: AxiosRequestConfig) => Promise<TData>;
    deleteThread: <TData = axios.AxiosResponse<DeleteThreadResponse, any>>(threadId: string, options?: AxiosRequestConfig) => Promise<TData>;
    listMessages: <TData = axios.AxiosResponse<ListMessagesResponse, any>>(threadId: string, params?: ListMessagesParams, options?: AxiosRequestConfig) => Promise<TData>;
    createMessage: <TData = axios.AxiosResponse<MessageObject, any>>(threadId: string, createMessageRequest: CreateMessageRequest, options?: AxiosRequestConfig) => Promise<TData>;
    getMessage: <TData = axios.AxiosResponse<MessageObject, any>>(threadId: string, messageId: string, options?: AxiosRequestConfig) => Promise<TData>;
    modifyMessage: <TData = axios.AxiosResponse<MessageObject, any>>(threadId: string, messageId: string, modifyMessageRequest: ModifyMessageRequest, options?: AxiosRequestConfig) => Promise<TData>;
    deleteMessage: <TData = axios.AxiosResponse<DeleteMessageResponse, any>>(threadId: string, messageId: string, options?: AxiosRequestConfig) => Promise<TData>;
    createThreadAndRun: <TData = axios.AxiosResponse<RunObject, any>>(createThreadAndRunRequest: CreateThreadAndRunRequest, options?: AxiosRequestConfig) => Promise<TData>;
    listRuns: <TData = axios.AxiosResponse<ListRunsResponse, any>>(threadId: string, params?: ListRunsParams, options?: AxiosRequestConfig) => Promise<TData>;
    createRun: <TData = axios.AxiosResponse<RunObject, any>>(threadId: string, createRunRequest: CreateRunRequest, options?: AxiosRequestConfig) => Promise<TData>;
    getRun: <TData = axios.AxiosResponse<RunObject, any>>(threadId: string, runId: string, options?: AxiosRequestConfig) => Promise<TData>;
    modifyRun: <TData = axios.AxiosResponse<RunObject, any>>(threadId: string, runId: string, modifyRunRequest: ModifyRunRequest, options?: AxiosRequestConfig) => Promise<TData>;
    submitToolOuputsToRun: <TData = axios.AxiosResponse<RunObject, any>>(threadId: string, runId: string, submitToolOutputsRunRequest: SubmitToolOutputsRunRequest, options?: AxiosRequestConfig) => Promise<TData>;
    cancelRun: <TData = axios.AxiosResponse<RunObject, any>>(threadId: string, runId: string, options?: AxiosRequestConfig) => Promise<TData>;
    listRunSteps: <TData = axios.AxiosResponse<ListRunStepsResponse, any>>(threadId: string, runId: string, params?: ListRunStepsParams, options?: AxiosRequestConfig) => Promise<TData>;
    getRunStep: <TData = axios.AxiosResponse<RunStepObject, any>>(threadId: string, runId: string, stepId: string, options?: AxiosRequestConfig) => Promise<TData>;
};
export type ListAssistantsResult = AxiosResponse<ListAssistantsResponse>;
export type CreateAssistantResult = AxiosResponse<AssistantObject>;
export type GetAssistantResult = AxiosResponse<AssistantObject>;
export type ModifyAssistantResult = AxiosResponse<AssistantObject>;
export type DeleteAssistantResult = AxiosResponse<DeleteAssistantResponse>;
export type CreateThreadResult = AxiosResponse<ThreadObject>;
export type GetThreadResult = AxiosResponse<ThreadObject>;
export type ModifyThreadResult = AxiosResponse<ThreadObject>;
export type DeleteThreadResult = AxiosResponse<DeleteThreadResponse>;
export type ListMessagesResult = AxiosResponse<ListMessagesResponse>;
export type CreateMessageResult = AxiosResponse<MessageObject>;
export type GetMessageResult = AxiosResponse<MessageObject>;
export type ModifyMessageResult = AxiosResponse<MessageObject>;
export type DeleteMessageResult = AxiosResponse<DeleteMessageResponse>;
export type CreateThreadAndRunResult = AxiosResponse<RunObject>;
export type ListRunsResult = AxiosResponse<ListRunsResponse>;
export type CreateRunResult = AxiosResponse<RunObject>;
export type GetRunResult = AxiosResponse<RunObject>;
export type ModifyRunResult = AxiosResponse<RunObject>;
export type SubmitToolOuputsToRunResult = AxiosResponse<RunObject>;
export type CancelRunResult = AxiosResponse<RunObject>;
export type ListRunStepsResult = AxiosResponse<ListRunStepsResponse>;
export type GetRunStepResult = AxiosResponse<RunStepObject>;
//# sourceMappingURL=assistants.d.ts.map