/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import {
  z as zod
} from 'zod';


/**
 * List uploaded certificates for this organization.
 * @summary List organization certificates
 */
export const listOrganizationCertificatesQueryLimitDefault = 20;export const listOrganizationCertificatesQueryOrderDefault = "desc";

export const listOrganizationCertificatesQueryParams = zod.object({
  "limit": zod.number().optional().describe('A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.\n'),
  "after": zod.string().optional().describe('A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.\n'),
  "order": zod.enum(['asc', 'desc']).optional().describe('Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.\n')
})

export const listOrganizationCertificatesResponse = zod.object({
  "data": zod.array(zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')),
  "first_id": zod.string().optional(),
  "last_id": zod.string().optional(),
  "has_more": zod.boolean(),
  "object": zod.enum(['list'])
})

/**
 * Upload a certificate to the organization. This does **not** automatically activate the certificate.

Organizations can upload up to 50 certificates.

 * @summary Upload certificate
 */
export const uploadCertificateBody = zod.object({
  "name": zod.string().optional().describe('An optional name for the certificate'),
  "content": zod.string().describe('The certificate content in PEM format')
})

export const uploadCertificateResponse = zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')

/**
 * Activate certificates at the organization level.

You can atomically and idempotently activate up to 10 certificates at a time.

 * @summary Activate certificates for organization
 */
export const activateOrganizationCertificatesBodyCertificateIdsMax = 10;


export const activateOrganizationCertificatesBody = zod.object({
  "certificate_ids": zod.array(zod.string()).min(1).max(activateOrganizationCertificatesBodyCertificateIdsMax)
})

export const activateOrganizationCertificatesResponse = zod.object({
  "data": zod.array(zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')),
  "first_id": zod.string().optional(),
  "last_id": zod.string().optional(),
  "has_more": zod.boolean(),
  "object": zod.enum(['list'])
})

/**
 * Deactivate certificates at the organization level.

You can atomically and idempotently deactivate up to 10 certificates at a time.

 * @summary Deactivate certificates for organization
 */
export const deactivateOrganizationCertificatesBodyCertificateIdsMax = 10;


export const deactivateOrganizationCertificatesBody = zod.object({
  "certificate_ids": zod.array(zod.string()).min(1).max(deactivateOrganizationCertificatesBodyCertificateIdsMax)
})

export const deactivateOrganizationCertificatesResponse = zod.object({
  "data": zod.array(zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')),
  "first_id": zod.string().optional(),
  "last_id": zod.string().optional(),
  "has_more": zod.boolean(),
  "object": zod.enum(['list'])
})

/**
 * Get a certificate that has been uploaded to the organization.

You can get a certificate regardless of whether it is active or not.

 * @summary Get certificate
 */
export const getCertificateParams = zod.object({
  "certificate_id": zod.string().describe('Unique ID of the certificate to retrieve.')
})

export const getCertificateQueryParams = zod.object({
  "include": zod.array(zod.enum(['content'])).optional().describe('A list of additional fields to include in the response. Currently the only supported value is `content` to fetch the PEM content of the certificate.')
})

export const getCertificateResponse = zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')

/**
 * Modify a certificate. Note that only the name can be modified.

 * @summary Modify certificate
 */
export const modifyCertificateParams = zod.object({
  "certificate_id": zod.string().describe('Unique ID of the certificate to modify.')
})

export const modifyCertificateBody = zod.object({
  "name": zod.string().describe('The updated name for the certificate')
})

export const modifyCertificateResponse = zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')

/**
 * Delete a certificate from the organization.

The certificate must be inactive for the organization and all projects.

 * @summary Delete certificate
 */
export const deleteCertificateParams = zod.object({
  "certificate_id": zod.string().describe('Unique ID of the certificate to delete.')
})

export const deleteCertificateResponse = zod.object({
  "object": zod.any().describe('The object type, must be `certificate.deleted`.'),
  "id": zod.string().describe('The ID of the certificate that was deleted.')
})

/**
 * List certificates for this project.
 * @summary List project certificates
 */
export const listProjectCertificatesParams = zod.object({
  "project_id": zod.string().describe('The ID of the project.')
})

export const listProjectCertificatesQueryLimitDefault = 20;export const listProjectCertificatesQueryOrderDefault = "desc";

export const listProjectCertificatesQueryParams = zod.object({
  "limit": zod.number().optional().describe('A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.\n'),
  "after": zod.string().optional().describe('A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.\n'),
  "order": zod.enum(['asc', 'desc']).optional().describe('Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.\n')
})

export const listProjectCertificatesResponse = zod.object({
  "data": zod.array(zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')),
  "first_id": zod.string().optional(),
  "last_id": zod.string().optional(),
  "has_more": zod.boolean(),
  "object": zod.enum(['list'])
})

/**
 * Activate certificates at the project level.

You can atomically and idempotently activate up to 10 certificates at a time.

 * @summary Activate certificates for project
 */
export const activateProjectCertificatesParams = zod.object({
  "project_id": zod.string().describe('The ID of the project.')
})

export const activateProjectCertificatesBodyCertificateIdsMax = 10;


export const activateProjectCertificatesBody = zod.object({
  "certificate_ids": zod.array(zod.string()).min(1).max(activateProjectCertificatesBodyCertificateIdsMax)
})

export const activateProjectCertificatesResponse = zod.object({
  "data": zod.array(zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')),
  "first_id": zod.string().optional(),
  "last_id": zod.string().optional(),
  "has_more": zod.boolean(),
  "object": zod.enum(['list'])
})

/**
 * Deactivate certificates at the project level. You can atomically and
idempotently deactivate up to 10 certificates at a time.

 * @summary Deactivate certificates for project
 */
export const deactivateProjectCertificatesParams = zod.object({
  "project_id": zod.string().describe('The ID of the project.')
})

export const deactivateProjectCertificatesBodyCertificateIdsMax = 10;


export const deactivateProjectCertificatesBody = zod.object({
  "certificate_ids": zod.array(zod.string()).min(1).max(deactivateProjectCertificatesBodyCertificateIdsMax)
})

export const deactivateProjectCertificatesResponse = zod.object({
  "data": zod.array(zod.object({
  "object": zod.enum(['certificate', 'organization.certificate', 'organization.project.certificate']).describe('The object type.\n\n- If creating, updating, or getting a specific certificate, the object type is `certificate`.\n- If listing, activating, or deactivating certificates for the organization, the object type is `organization.certificate`.\n- If listing, activating, or deactivating certificates for a project, the object type is `organization.project.certificate`.\n'),
  "id": zod.string().describe('The identifier, which can be referenced in API endpoints'),
  "name": zod.string().describe('The name of the certificate.'),
  "created_at": zod.number().describe('The Unix timestamp (in seconds) of when the certificate was uploaded.'),
  "certificate_details": zod.object({
  "valid_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate becomes valid.'),
  "expires_at": zod.number().optional().describe('The Unix timestamp (in seconds) of when the certificate expires.'),
  "content": zod.string().optional().describe('The content of the certificate in PEM format.')
}),
  "active": zod.boolean().optional().describe('Whether the certificate is currently active at the specified scope. Not returned when getting details for a specific certificate.')
}).describe('Represents an individual `certificate` uploaded to the organization.')),
  "first_id": zod.string().optional(),
  "last_id": zod.string().optional(),
  "has_more": zod.boolean(),
  "object": zod.enum(['list'])
})

