/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Certificate,
  DeleteCertificateResponse,
  GetCertificateParams,
  ListCertificatesResponse,
  ListOrganizationCertificatesParams,
  ListProjectCertificatesParams,
  ModifyCertificateRequest,
  ToggleCertificatesRequest,
  UploadCertificateRequest
} from '.././schema';




  export const getCertificates = () => {
/**
 * List uploaded certificates for this organization.
 * @summary List organization certificates
 */
const listOrganizationCertificates = <TData = AxiosResponse<ListCertificatesResponse>>(
    params?: ListOrganizationCertificatesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/certificates`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Upload a certificate to the organization. This does **not** automatically activate the certificate.

Organizations can upload up to 50 certificates.

 * @summary Upload certificate
 */
const uploadCertificate = <TData = AxiosResponse<Certificate>>(
    uploadCertificateRequest: UploadCertificateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/certificates`,
      uploadCertificateRequest,options
    );
  }
/**
 * Activate certificates at the organization level.

You can atomically and idempotently activate up to 10 certificates at a time.

 * @summary Activate certificates for organization
 */
const activateOrganizationCertificates = <TData = AxiosResponse<ListCertificatesResponse>>(
    toggleCertificatesRequest: ToggleCertificatesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/certificates/activate`,
      toggleCertificatesRequest,options
    );
  }
/**
 * Deactivate certificates at the organization level.

You can atomically and idempotently deactivate up to 10 certificates at a time.

 * @summary Deactivate certificates for organization
 */
const deactivateOrganizationCertificates = <TData = AxiosResponse<ListCertificatesResponse>>(
    toggleCertificatesRequest: ToggleCertificatesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/certificates/deactivate`,
      toggleCertificatesRequest,options
    );
  }
/**
 * Get a certificate that has been uploaded to the organization.

You can get a certificate regardless of whether it is active or not.

 * @summary Get certificate
 */
const getCertificate = <TData = AxiosResponse<Certificate>>(
    certificateId: string,
    params?: GetCertificateParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/certificates/${certificateId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Modify a certificate. Note that only the name can be modified.

 * @summary Modify certificate
 */
const modifyCertificate = <TData = AxiosResponse<Certificate>>(
    certificateId: string,
    modifyCertificateRequest: ModifyCertificateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/certificates/${certificateId}`,
      modifyCertificateRequest,options
    );
  }
/**
 * Delete a certificate from the organization.

The certificate must be inactive for the organization and all projects.

 * @summary Delete certificate
 */
const deleteCertificate = <TData = AxiosResponse<DeleteCertificateResponse>>(
    certificateId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/organization/certificates/${certificateId}`,options
    );
  }
/**
 * List certificates for this project.
 * @summary List project certificates
 */
const listProjectCertificates = <TData = AxiosResponse<ListCertificatesResponse>>(
    projectId: string,
    params?: ListProjectCertificatesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/organization/projects/${projectId}/certificates`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Activate certificates at the project level.

You can atomically and idempotently activate up to 10 certificates at a time.

 * @summary Activate certificates for project
 */
const activateProjectCertificates = <TData = AxiosResponse<ListCertificatesResponse>>(
    projectId: string,
    toggleCertificatesRequest: ToggleCertificatesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}/certificates/activate`,
      toggleCertificatesRequest,options
    );
  }
/**
 * Deactivate certificates at the project level. You can atomically and
idempotently deactivate up to 10 certificates at a time.

 * @summary Deactivate certificates for project
 */
const deactivateProjectCertificates = <TData = AxiosResponse<ListCertificatesResponse>>(
    projectId: string,
    toggleCertificatesRequest: ToggleCertificatesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/organization/projects/${projectId}/certificates/deactivate`,
      toggleCertificatesRequest,options
    );
  }
return {listOrganizationCertificates,uploadCertificate,activateOrganizationCertificates,deactivateOrganizationCertificates,getCertificate,modifyCertificate,deleteCertificate,listProjectCertificates,activateProjectCertificates,deactivateProjectCertificates}};
export type ListOrganizationCertificatesResult = AxiosResponse<ListCertificatesResponse>
export type UploadCertificateResult = AxiosResponse<Certificate>
export type ActivateOrganizationCertificatesResult = AxiosResponse<ListCertificatesResponse>
export type DeactivateOrganizationCertificatesResult = AxiosResponse<ListCertificatesResponse>
export type GetCertificateResult = AxiosResponse<Certificate>
export type ModifyCertificateResult = AxiosResponse<Certificate>
export type DeleteCertificateResult = AxiosResponse<DeleteCertificateResponse>
export type ListProjectCertificatesResult = AxiosResponse<ListCertificatesResponse>
export type ActivateProjectCertificatesResult = AxiosResponse<ListCertificatesResponse>
export type DeactivateProjectCertificatesResult = AxiosResponse<ListCertificatesResponse>
