/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateEmbeddingRequest,
  CreateEmbeddingResponse
} from '.././schema';




  export const getEmbeddings = () => {
/**
 * Creates an embedding vector representing the input text.
 * @summary Create embeddings
 */
const createEmbedding = <TData = AxiosResponse<CreateEmbeddingResponse>>(
    createEmbeddingRequest: CreateEmbeddingRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/embeddings`,
      createEmbeddingRequest,options
    );
  }
return {createEmbedding}};
export type CreateEmbeddingResult = AxiosResponse<CreateEmbeddingResponse>
