/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * OpenAPI spec version: 2.3.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { CreateImageEditRequest, CreateImageRequest, CreateImageVariationRequest, ImagesResponse } from '.././schema';
export declare const getImages: () => {
    createImage: <TData = axios.AxiosResponse<ImagesResponse, any>>(createImageRequest: CreateImageRequest, options?: AxiosRequestConfig) => Promise<TData>;
    createImageEdit: <TData = axios.AxiosResponse<ImagesResponse, any>>(createImageEditRequest: CreateImageEditRequest, options?: AxiosRequestConfig) => Promise<TData>;
    createImageVariation: <TData = axios.AxiosResponse<ImagesResponse, any>>(createImageVariationRequest: CreateImageVariationRequest, options?: AxiosRequestConfig) => Promise<TData>;
};
export type CreateImageResult = AxiosResponse<ImagesResponse>;
export type CreateImageEditResult = AxiosResponse<ImagesResponse>;
export type CreateImageVariationResult = AxiosResponse<ImagesResponse>;
//# sourceMappingURL=images.d.ts.map